package com.elsevier.reaxys;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;

/**
 * enumeration with labels for the data fields in Reaxys.  This is used to map the field
 * names to more meaningful labels in the output.
 * 
 * @date 19 aug 2014
 * @revised Feb 2015
 * @revised Aug 2015 with PubChem, eMolecules, ELN fields
 * @revised Jul 2018 with misc update date fields
 * @revised Jan 2021 with Commercial Substances fields
 * 
 * @author CLARKM
 * @author TOM W
 *
 */
public enum ReaxysFieldTypes {
	
	FA ("Field Availability", "FA.FA"),
	RA ("Reaction Availability", "RA.RA"),
	CA ("Citation Availability", "CA.CA"),
	DX ("Bioactivity Data Point Availability", "DX.DX"),
	TX ("Target Availability", "TX.TX"),
	BI ("Basic Indexes", "BI.BI"),
	ID ("Identification", "ID.ID"),
	IDE ("Substance Identification", "IDE.IDE"),
	LIGO ("One-Center Ligands", "LIGO.LIGO"),
	LIGM ("Multi-Center Ligands", "LIGM.LIGM"),
	ALLOY ("Alloy Composition", "ALLOY.ALLOY"),
	YY ("Structure", "YY.YY"),
	SUBLINK ("Database Link", "SUBLINK.SUBLINK"),
	LB ("Substance Label", "LB.LB"),
	PSD ("Patent-Specific Data", "PSD.PSD"),
	SEQ ("Sequence", "SEQ.SEQ"),
	CALC ("Druglikeness", "CALC.CALC"),
	CLPHASE ("Highest Clinical Phase", "CLPHASE.CLPHASE"),
	EXTID ("External Identifiers", "EXTID.EXTID"),
	RSTR ("Related Structure", "RSTR.RSTR"),
	CAT ("Catalyst Investigation", "CAT.CAT"),
	CDER ("Derivative", "CDER.CDER"),
	PUR ("Purification", "PUR.PUR"),
	SOVERW ("Substance overview", "SOVERW.SOVERW"),
	BIB ("Bibliographic Data", "BIB.BIB"),
	CNR ("Citation Number", "CNR.CNR"),
	CIT ("Citation", "CIT.CIT"),
	AB ("Abstract", "AB.AB"),
	KWD ("Keywords", "KWD.KWD"),
	PBIB ("Patent Bibliography", "PBIB.PBIB"),
	CHE ("Reaction Data", "CHE.CHE"),
	RX ("Reaction", "RX.RX"),
	RXNLINK ("Reaction Link", "RXNLINK.RXNLINK"),
	RXD ("Reaction Details", "RXD.RXD"),
	PHY ("Physical Data", "PHY.PHY"),
	MP ("Melting Point", "MP.MP"),
	BP ("Boiling Point", "BP.BP"),
	SP ("Sublimation", "SP.SP"),
	RI ("Refractive Index", "RI.RI"),
	DEN ("Density", "DEN.DEN"),
	CNF ("Conformation", "CNF.CNF"),
	IDA ("Interatomic Distances and Angles", "IDA.IDA"),
	EM ("Electrical Moment", "EM.EM"),
	ELP ("Electrical Polarizability", "ELP.ELP"),
	DFM ("Molecular Deformation", "DFM.DFM"),
	EBC ("Energy Barriers", "EBC.EBC"),
	EDIS ("Dissociation Energy", "EDIS.EDIS"),
	IP ("Ionization Potential", "IP.IP"),
	CIP ("Electron Binding", "CIP.CIP"),
	CPD ("Crystal Property Description", "CPD.CPD"),
	CRYPH ("Crystal Phase", "CRYPH.CRYPH"),
	DP ("Decomposition", "DP.DP"),
	TP ("Triple Point", "TP.TP"),
	CPTP ("Transition Point(s) of Crystalline Modification(s)", "CPTP.CPTP"),
	CSYS ("Crystal System", "CSYS.CSYS"),
	CSG ("Space Group", "CSG.CSG"),
	CDEN ("Density of the Crystal", "CDEN.CDEN"),
	LIQPH ("Liquid Phase", "LIQPH.LIQPH"),
	LPTP ("Transition Point(s) of Liquid Modification(s)", "LPTP.LPTP"),
	CRT ("Critical Temperature", "CRT.CRT"),
	CRP ("Critical Pressure", "CRP.CRP"),
	CRD ("Critical Density", "CRD.CRD"),
	CRV ("Critical Volume", "CRV.CRV"),
	VP ("Vapour Pressure", "VP.VP"),
	GP ("Gas Phase", "GP.GP"),
	MEC ("Mechanical Properties", "MEC.MEC"),
	COMP ("Compressibility", "COMP.COMP"),
	SOUND ("Sound Properties", "SOUND.SOUND"),
	ST ("Surface Tension", "ST.ST"),
	DV ("Dynamic Viscosity", "DV.DV"),
	KV ("Kinematic Viscosity", "KV.KV"),
	BV ("Bulk Viscosity", "BV.BV"),
	SDIF ("Self-diffusion", "SDIF.SDIF"),
	CHROMAT ("Chromatographic Data", "CHROMAT.CHROMAT"),
	TD ("Transport Data", "TD.TD"),
	TEXP ("Thermal Expansion", "TEXP.TEXP"),
	HCOM ("Enthalpy of Combustion", "HCOM.HCOM"),
	HFOR ("Enthalpy of Formation", "HFOR.HFOR"),
	HHDG ("Enthalpy of Hydrogenation", "HHDG.HHDG"),
	HFUS ("Enthalpy of Fusion", "HFUS.HFUS"),
	HVAP ("Enthalpy of Vaporization", "HVAP.HVAP"),
	HSP ("Enthalpy of Sublimation", "HSP.HSP"),
	HPTP ("Enthalpies of Other Phase Transitions", "HPTP.HPTP"),
	CP ("Heat Capacity Cp", "CP.CP"),
	CP0 ("Heat Capacity Cp0", "CP0.CP0"),
	CV ("Heat Capacity Cv", "CV.CV"),
	OTHE ("Other Thermochemical Data", "OTHE.OTHE"),
	OPT ("Optics", "OPT.OPT"),
	ORP ("Optical Rotatory Power", "ORP.ORP"),
	MUT ("Mutarotation", "MUT.MUT"),
	CDIC ("Circular Dichroism", "CDIC.CDIC"),
	ORD ("Optical Rotatory Dispersion", "ORD.ORD"),
	MSUS ("Magnetic Susceptibility", "MSUS.MSUS"),
	MAG ("Magnetic Data", "MAG.MAG"),
	SDIC ("Static Dielectric Constant", "SDIC.SDIC"),
	DIC ("Dielectric Constant", "DIC.DIC"),
	ELE ("Electrical Data", "ELE.ELE"),
	ELCB ("Electrochemical Behaviour", "ELCB.ELCB"),
	DE ("Dissociation Exponent", "DE.DE"),
	IEP ("Isoelectric Point  pH", "IEP.IEP"),
	POT ("Electrochemical Characteristics", "POT.POT"),
	ELYC ("Electrolytic Conductivity", "ELYC.ELYC"),
	ELCH ("Electrochemistry Data", "ELCH.ELCH"),
	XS ("Cross-Sections", "XS.XS"),
	FLAP ("Flash Point", "FLAP.FLAP"),
	AUTI ("Autoignition", "AUTI.AUTI"),
	EXPL ("Explosion Limits", "EXPL.EXPL"),
	FINFO ("Further Information", "FINFO.FINFO"),
	SLB ("Solubility (MCS)", "SLB.SLB"),
	SLBP ("Solubility Product (MCS)", "SLBP.SLBP"),
	SOLM ("Solution Behaviour (MCS)", "SOLM.SOLM"),
	CMC ("Critical Micelle Concentration (MCS)", "CMC.CMC"),
	HEN ("Henry Constant (MCS)", "HEN.HEN"),
	POW ("Partition octan-1-ol/water (MCS)", "POW.POW"),
	LVSM ("Liquid/Vapour Systems (MCS)", "LVSM.LVSM"),
	AZE ("Azeotropes (MCS)", "AZE.AZE"),
	CPEM ("Complex Phase Equilibria (MCS)", "CPEM.CPEM"),
	LLSM ("Liquid/Liquid Systems (MCS)", "LLSM.LLSM"),
	LSSM ("Liquid/Solid Systems (MCS)", "LSSM.LSSM"),
	MECM ("Mechanical & Physical Properties (MCS)", "MECM.MECM"),
	TRAM ("Transport Phenomena (MCS)", "TRAM.TRAM"),
	ENEM ("Energy Data (MCS)", "ENEM.ENEM"),
	EDM ("Electrical Data (MCS)", "EDM.EDM"),
	ODM ("Optical Data (MCS)", "ODM.ODM"),
	BSPM ("Boundary Surface Phenomena (MCS)", "BSPM.BSPM"),
	ADSM ("Adsorption (MCS)", "ADSM.ADSM"),
	ASSM ("Association (MCS)", "ASSM.ASSM"),
	SPE ("Spectra", "SPE.SPE"),
	NMR ("NMR Spectroscopy", "NMR.NMR"),
	IR ("IR Spectroscopy", "IR.IR"),
	MS ("Mass Spectrometry", "MS.MS"),
	UV ("UV/VIS Spectroscopy", "UV.UV"),
	ESR ("ESR Spectroscopy", "ESR.ESR"),
	NQR ("NQR Spectroscopy", "NQR.NQR"),
	ROT ("Rotational Spectroscopy", "ROT.ROT"),
	RAMAN ("Raman Spectroscopy", "RAMAN.RAMAN"),
	LUM ("Luminescence Spectroscopy", "LUM.LUM"),
	FLU ("Fluorescence Spectroscopy", "FLU.FLU"),
	PHO ("Phosphorescence Spectroscopy", "PHO.PHO"),
	OSM ("Other Spectroscopic Methods", "OSM.OSM"),
	PED ("Bioactivity", "PED.PED"),
	PHARM ("Pharmacological Data", "PHARM.PHARM"),
	ECT ("Ecotoxicology", "ECT.ECT"),
	ECO ("Ecological Data", "ECO.ECO"),
	ECA ("Exposure Assessment", "ECA.ECA"),
	ECC ("Concentration in the Environment", "ECC.ECC"),
	ECTD ("Transport and Distribution", "ECTD.ECTD"),
	BIO ("Bioaccumulation, Biomagnification and Biomonitoring", "BIO.BIO"),
	BIOD ("Biodegradation", "BIOD.BIOD"),
	ECDH ("Abiotic Degradation, Hydrolysis", "ECDH.ECDH"),
	ECDP ("Abiotic Degradation, Photolysis", "ECDP.ECDP"),
	ECS ("Stability in Soil", "ECS.ECS"),
	EOD ("Oxygen Demand", "EOD.EOD"),
	USA ("Use/Application", "USA.USA"),
	USE ("Use", "USE.USE"),
	NPR ("Natural Product", "NPR.NPR"),
	INP ("Isolation from Natural Product", "INP.INP"),
	QUANT ("Quantum Chemical Data", "QUANT.QUANT"),
	QUAN ("Quantum Chemical Calculations", "QUAN.QUAN"),
	DATS ("Bioactivities", "DATS.DATS"),
	DAT ("Bioactivity", "DAT.DAT"),
	DATE ("Entry Date", "DAT.ED"),
	DATU ("Update Date", "DAT.UPD"),
	TGI ("Targets", "TGI.TGI"),
	TARGET ("Target", "TARGET.TARGET"),
	SUBUNIT ("Subunit", "SUBUNIT.SUBUNIT"),
	TOVERW ("Target overview", "TOVERW.TOVERW"),
	FA_FA ("Field Availability", "FA.FA"),
	RA_RA ("Reaction Availability", "RA.RA"),
	CA_CA ("Citation Availability", "CA.CA"),
	DX_DX ("Bioactivity Data Point Availability", "DX.DX"),
	TX_TX ("Target Availability", "TX.TX"),
	BI_BISUB ("Substance Basic Index", "BI.BISUB"),
	BI_BIREA ("Reaction Basic Index", "BI.BIREA"),
	BI_BICIT ("Citation Basic Index", "BI.BICIT"),
	YY_STR ("Structure", "YY.STR"),
	LB_L ("Citation", "LB.L"),
	LB_SOURCE ("Source", "LB.SOURCE"),
	LB_LB ("Label", "LB.LB"),
	LB_ED ("Entry Date", "LB.ED"),
	AB_TI ("Title", "AB.TI"),
	AB_AB ("Abstract", "AB.AB"),
	AB_ALA ("Language", "AB.ALA"),
	AB_KW ("Keywords", "AB.KW"),
	RX_ID ("Reaction ID", "RX.ID"),
	RX_RXRN ("Reactant XRN", "RX.RXRN"),
	RX_RCT ("Reactant", "RX.RCT"),
	RX_PXRN ("Product XRN", "RX.PXRN"),
	RX_PRO ("Product", "RX.PRO"),
	RX_BLA ("Chemical Behavior reactants", "RX.BLA"),
	RX_BLB ("Preparation reactants", "RX.BLB"),
	RX_BLC ("Detailed R. reactants", "RX.BLC"),
	RX_NVAR ("Number of Reaction Details", "RX.NVAR"),
	RX_BIN ("Bin", "RX.BIN"),
	RX_BFREQ ("Bin Frequency", "RX.BFREQ"),
	RX_BRANGE ("Bin Range", "RX.BRANGE"),
	RX_BNAME ("Bin Name", "RX.BNAME"),
	RX_RXNFILE ("Rxnfile", "RX.RXNFILE"),
	RX_REG ("Registration String", "RX.REG"),
	RX_RANK ("Reaction Rank", "RX.RANK"),
	RX_MYD ("Maximum Yield", "RX.MYD"),
	RX_SKW ("Reaction Structure Keywords", "RX.SKW"),
	RX_RTYP ("Record Type", "RX.RTYP"),
	RX_TNAME ("Reaction Name", "RX.TNAME"),
	RX_RAVAIL ("Reactant Availability", "RX.RAVAIL"),
	RX_PAVAIL ("Product Availability", "RX.PAVAIL"),
	RX_MAXPUB ("Maximum Publication Year", "RX.MAXPUB"),
	RX_NUMREF ("Number of References", "RX.NUMREF"),
	RX_MAXPMW ("Maximum Product Molweight", "RX.MAXPMW"),
	RX_ED ("Reaction Entry Date", "RX.ED"),
	RX_UPD ("Reaction Update Date", "RX.UPD"),
	RY_STR ("Rxnfile", "RY.STR"),
	RY_PRO ("Product structure(s)", "RY.PRO"),
	RY_RCT ("Reactant structure(s)", "RY.RCT"),
	MP_L ("Citation Pointer", "MP.L"),
	MP_SOURCE ("Source", "MP.SOURCE"),
	MP_SOL ("Solvent", "MP.SOL"),
	MP_CSOL ("Crystallizes With", "MP.CSOL"),
	MP_AMNT ("Amount", "MP.AMNT"),
	MP_ED ("Entry Date", "MP.ED"),
	MP_LCN ("Location", "MP.LCN"),
	MP_TAG ("Tag Location", "MP.TAG"),
	MP_COM ("Comment", "MP.COM"),
	BP_L ("Citation Pointer", "BP.L"),
	BP_SOURCE ("Source", "BP.SOURCE"),
	BP_P ("Pressure", "BP.P"),
	BP_ED ("Entry Date", "BP.ED"),
	BP_LCN ("Location", "BP.LCN"),
	BP_TAG ("Tag Location", "BP.TAG"),
	BP_COM ("Comment", "BP.COM"),
	SP_L ("Citation Pointer", "SP.L"),
	SP_SOURCE ("Source", "SP.SOURCE"),
	SP_P ("Pressure", "SP.P"),
	SP_ED ("Entry Date", "SP.ED"),
	SP_LCN ("Location", "SP.LCN"),
	SP_TAG ("Tag Location", "SP.TAG"),
	SP_COM ("Comment", "SP.COM"),
	RI_L ("Citation Pointer", "RI.L"),
	RI_SOURCE ("Source", "RI.SOURCE"),
	RI_W ("Wavelength", "RI.W"),
	RI_T ("Temperature", "RI.T"),
	RI_ED ("Entry Date", "RI.ED"),
	RI_LCN ("Location", "RI.LCN"),
	RI_TAG ("Tag Location", "RI.TAG"),
	RI_COM ("Comment", "RI.COM"),
	EM_L ("Citation Pointer", "EM.L"),
	EM_SOURCE ("Source", "EM.SOURCE"),
	EM_KW ("Description", "EM.KW"),
	EM_T ("Temperature", "EM.T"),
	EM_MET ("Method", "EM.MET"),
	EM_SOL ("Solvent", "EM.SOL"),
	EM_ED ("Entry Date", "EM.ED"),
	EM_LCN ("Location", "EM.LCN"),
	EM_TAG ("Tag Location", "EM.TAG"),
	EM_COM ("Comment", "EM.COM"),
	IP_L ("Citation Pointer", "IP.L"),
	IP_SOURCE ("Source", "IP.SOURCE"),
	IP_MET ("Method", "IP.MET"),
	IP_ED ("Entry Date", "IP.ED"),
	IP_LCN ("Location", "IP.LCN"),
	IP_TAG ("Tag Location", "IP.TAG"),
	IP_COM ("Comment", "IP.COM"),
	DP_L ("Citation Pointer", "DP.L"),
	DP_SOURCE ("Source", "DP.SOURCE"),
	DP_SOL ("Solvent", "DP.SOL"),
	DP_CRSOL ("Solvent for Crystallization", "DP.CRSOL"),
	DP_SOLM ("Amount", "DP.SOLM"),
	DP_ED ("Entry Date", "DP.ED"),
	DP_LCN ("Location", "DP.LCN"),
	DP_TAG ("Tag Location", "DP.TAG"),
	DP_COM ("Comment", "DP.COM"),
	TP_L ("Citation Pointer", "TP.L"),
	TP_SOURCE ("Source", "TP.SOURCE"),
	TP_ED ("Entry Date", "TP.ED"),
	TP_LCN ("Location", "TP.LCN"),
	TP_TAG ("Tag Location", "TP.TAG"),
	TP_COM ("Comment", "TP.COM"),
	VP_L ("Citation Pointer", "VP.L"),
	VP_SOURCE ("Source", "VP.SOURCE"),
	VP_T ("Temperature", "VP.T"),
	VP_ED ("Entry Date", "VP.ED"),
	VP_LCN ("Location", "VP.LCN"),
	VP_TAG ("Tag Location", "VP.TAG"),
	VP_COM ("Comment", "VP.COM"),
	GP_L ("Citation Pointer", "GP.L"),
	GP_SOURCE ("Source", "GP.SOURCE"),
	GP_KW ("Description", "GP.KW"),
	GP_ED ("Entry Date", "GP.ED"),
	GP_LCN ("Location", "GP.LCN"),
	GP_TAG ("Tag Location", "GP.TAG"),
	GP_COM ("Comment", "GP.COM"),
	ST_L ("Citation Pointer", "ST.L"),
	ST_SOURCE ("Source", "ST.SOURCE"),
	ST_T ("Temperature", "ST.T"),
	ST_ED ("Entry Date", "ST.ED"),
	ST_LCN ("Location", "ST.LCN"),
	ST_TAG ("Tag Location", "ST.TAG"),
	ST_COM ("Comment", "ST.COM"),
	DV_L ("Citation Pointer", "DV.L"),
	DV_SOURCE ("Source", "DV.SOURCE"),
	DV_MEA ("Kind of measurement", "DV.MEA"),
	DV_T ("Temperature", "DV.T"),
	DV_ED ("Entry Date", "DV.ED"),
	DV_LCN ("Location", "DV.LCN"),
	DV_TAG ("Tag Location", "DV.TAG"),
	DV_COM ("Comment", "DV.COM"),
	KV_L ("Citation Pointer", "KV.L"),
	KV_SOURCE ("Source", "KV.SOURCE"),
	KV_MEA ("Kind of measurement", "KV.MEA"),
	KV_T ("Temperature", "KV.T"),
	KV_ED ("Entry Date", "KV.ED"),
	KV_LCN ("Location", "KV.LCN"),
	KV_TAG ("Tag Location", "KV.TAG"),
	KV_COM ("Comment", "KV.COM"),
	BV_L ("Citation Pointer", "BV.L"),
	BV_SOURCE ("Source", "BV.SOURCE"),
	BV_T ("Temperature", "BV.T"),
	BV_ED ("Entry Date", "BV.ED"),
	BV_LCN ("Location", "BV.LCN"),
	BV_TAG ("Tag Location", "BV.TAG"),
	BV_COM ("Comment", "BV.COM"),
	TD_L ("Citation Pointer", "TD.L"),
	TD_SOURCE ("Source", "TD.SOURCE"),
	TD_KW ("Description", "TD.KW"),
	TD_ED ("Entry Date", "TD.ED"),
	TD_LCN ("Location", "TD.LCN"),
	TD_TAG ("Tag Location", "TD.TAG"),
	TD_COM ("Comment", "TD.COM"),
	CP_L ("Citation Pointer", "CP.L"),
	CP_SOURCE ("Source", "CP.SOURCE"),
	CP_T ("Temperature", "CP.T"),
	CP_ED ("Entry Date", "CP.ED"),
	CP_LCN ("Location", "CP.LCN"),
	CP_TAG ("Tag Location", "CP.TAG"),
	CP_COM ("Comment", "CP.COM"),
	CV_L ("Citation Pointer", "CV.L"),
	CV_SOURCE ("Source", "CV.SOURCE"),
	CV_T ("Temperature", "CV.T"),
	CV_ED ("Entry Date", "CV.ED"),
	CV_LCN ("Location", "CV.LCN"),
	CV_TAG ("Tag Location", "CV.TAG"),
	CV_COM ("Comment", "CV.COM"),
	DE_L ("Citation Pointer", "DE.L"),
	DE_SOURCE ("Source", "DE.SOURCE"),
	DE_GRP ("Dissociation Group", "DE.GRP"),
	DE_T ("Temperature", "DE.T"),
	DE_SOL ("Solvent", "DE.SOL"),
	DE_MET ("Method", "DE.MET"),
	DE_TYP ("Type", "DE.TYP"),
	DE_ED ("Entry Date", "DE.ED"),
	DE_LCN ("Location", "DE.LCN"),
	DE_TAG ("Tag Location", "DE.TAG"),
	DE_COM ("Comment", "DE.COM"),
	XS_L ("Citation Pointer", "XS.L"),
	XS_SOURCE ("Source", "XS.SOURCE"),
	XS_KW ("Description", "XS.KW"),
	XS_ED ("Entry Date", "XS.ED"),
	XS_LCN ("Location", "XS.LCN"),
	XS_TAG ("Tag Location", "XS.TAG"),
	XS_COM ("Comment", "XS.COM"),
	IR_L ("Citation Pointer", "IR.L"),
	IR_SOURCE ("Source", "IR.SOURCE"),
	IR_KW ("Description", "IR.KW"),
	IR_SOL ("Solvent", "IR.SOL"),
	IR_T ("Temperature", "IR.T"),
	IR_TXT ("Original Text", "IR.TXT"),
	IR_SIG ("Signals", "IR.SIG"),
	IR_INT ("Intensity", "IR.INT"),
	IR_ED ("Entry Date", "IR.ED"),
	IR_LCN ("Location", "IR.LCN"),
	IR_TAG ("Tag Location", "IR.TAG"),
	IR_COM ("Comment", "IR.COM"),
	MS_L ("Citation Pointer", "MS.L"),
	MS_SOURCE ("Source", "MS.SOURCE"),
	MS_KW ("Description", "MS.KW"),
	MS_SIG ("Peak", "MS.SIG"),
	MS_INT ("Intensity", "MS.INT"),
	MS_ED ("Entry Date", "MS.ED"),
	MS_LCN ("Location", "MS.LCN"),
	MS_TAG ("Tag Location", "MS.TAG"),
	MS_COM ("Comment", "MS.COM"),
	UV_L ("Citation Pointer", "UV.L"),
	UV_SOURCE ("Source", "UV.SOURCE"),
	UV_KW ("Description", "UV.KW"),
	UV_SOL ("Solvent", "UV.SOL"),
	UV_AM ("Absorption Maxima", "UV.AM"),
	UV_EAC ("Ext./Abs. Coefficient", "UV.EAC"),
	UV_LOGE ("Log epsilon", "UV.LOGE"),
	UV_ED ("Entry Date", "UV.ED"),
	UV_LCN ("Location", "UV.LCN"),
	UV_TAG ("Tag Location", "UV.TAG"),
	UV_COM ("Comment", "UV.COM"),
	IDE_END ("Entry Date", "IDE.ED"),
	IDE_UD ("Update Date", "IDE.UD"),
	IDE_XRN ("Reaxys Registry Number", "IDE.XRN"),
	IDE_XPR ("Preferred RN", "IDE.XPR"),
	IDE_RN ("CAS Registry Number", "IDE.RN"),
	IDE_PCID ("PubChem Compound ID", "IDE.PID"),
    IDE_SYN ("Synonyms", "IDE.SYN"),
	IDE_EID ("eMolecules Compound ID", "IDE.EID"),
    IDE_LNID ("LabNetworks Compound ID", "IDE.LNID"),
    IDE_SAID ("SigmaAldrich Compound ID", "IDE.SAID"),
    IDE_VERS("Version ID", "IDE.VERSIONID"),
	IDE_PARENT("Parent ID", "IDE.PARENTID"),
	IDE_CTYPE("Compound Type", "IDE.CTYPE"),
	IDE_CASRN("CAS Registry Number", "IDE.CASRN"),
	IDE_LINK ("External Link",  "IDE.LINK"),
	IDE_CHEMSEG("Chemical Name Segment",  "IDE.CNS"),
	IDE_CN ("Chemical Name", "IDE.CN"),
	IDE_REG ("Registration String", "IDE.REG"),
	IDE_RCSID ("Reaxys Commercial Substance ID", "IDE.RCSID"),
	IDE_LSF ("Linear Structure Formula", "IDE.LSF"),
	IDE_FMF ("Fragment Molecular Formula", "IDE.FMF"),
	IDE_MF ("Molecular Formula", "IDE.MF"),
	IDE_HSF ("Hill Formula", "IDE.HSF"),
	IDE_IMF ("Molecular Formula with Isotopes", "IDE.IMF"),
	IDE_IHSF ("Hill Formula with Isotopes", "IDE.IHSF"),
	IDE_MOFO ("Search MF Range", "IDE.MOFO"),
	IDE_CHA ("Charge", "IDE.CHA"),
	IDE_ELC ("Element Counts", "IDE.ELC"),
	IDE_IELC ("Element Counts with Isotopes", "IDE.IELC"),
	IDE_ELS ("Element Symbols", "IDE.ELS"),
	IDE_NA ("Number of Atoms", "IDE.NA"),
	IDE_NE ("Number of Elements", "IDE.NE"),
	IDE_NF ("Number of Fragments", "IDE.NF"),
	IDE_NC ("Number of Components", "IDE.NC"),
	IDE_NI ("Number of Isotopes", "IDE.NI"),
	IDE_INE ("Number of Elements with Isotopes", "IDE.INE"),
	IDE_MW ("Molecular Weight", "IDE.MW"),
	IDE_STYPE ("Type of Substance", "IDE.STYPE"),
	IDE_TYPMOD ("Type and Modification", "IDE.TYPMOD"),
	IDE_INCHI ("InChI Key", "IDE.INCHI"),
	IDE_INCHA ("Alternate InChI Key", "IDE.INCHA"),
	IDE_AVAIL ("Availability", "IDE.AVAIL"),
	IDE_MAXPUB ("Maximum Publication Year", "IDE.MAXPUB"),
	IDE_NUMREF ("Number of References", "IDE.NUMREF"),
	IDE_MARKREF ("Markush Reference Count", "IDE.MARKREF"),
	IDE_FULLRXNS ("Full Reaction Count", "IDE.FULLRXNS"),
	IDE_HASBIO ("Bioactivity Presence", "IDE.HASBIO"),
	IDE_ED ("Entry Date", "IDE.ED"),
	IDE_UPD ("Update Date", "IDE.UPD"),
	PSD_L ("Citation", "PSD.L"),
	PSD_SOURCE ("Source", "PSD.SOURCE"),
	PSD_PRC ("Prophetic Compound", "PSD.PRC"),
	PSD_MARPRN ("Related Markush Structure (RN)", "PSD.MARPRN"),
	PSD_LCN ("Location in Patent", "PSD.LCN"),
	PSD_TAG ("Tag Location", "PSD.TAG"),
	PSD_ED ("Entry Date", "PSD.ED"),
	SEQ_PEPTIDE ("Peptide flag", "SEQ.PEPTIDE"),
	SEQ_SEQUENCE ("Sequence", "SEQ.SEQUENCE"),
	SEQ_SEQHASH ("Sequence Hash", "SEQ.SEQHASH"),
	CAT_L ("Citation Pointer", "CAT.L"),
	CAT_SOURCE ("Source", "CAT.SOURCE"),
	CAT_CHAR ("Investigated characteristic(s)", "CAT.CHAR"),
	CAT_SPEC ("Specification of catalysis", "CAT.SPEC"),
	CAT_CLASS ("Classification of catalysis", "CAT.CLASS"),
	CAT_REA ("Type of reaction", "CAT.REA"),
	CAT_CCXRN ("Co-catalyst/co-substrate XRN", "CAT.CCXRN"),
	CAT_CCN ("Co-catalyst/co-substrate name", "CAT.CCN"),
	CAT_ED ("Entry Date", "CAT.ED"),
	CAT_LCN ("Location", "CAT.LCN"),
	CAT_TAG ("Tag Location", "CAT.TAG"),
	CAT_COM ("Comment", "CAT.COM"),
	PUR_L ("Citation Pointer", "PUR.L"),
	PUR_SOURCE ("Source", "PUR.SOURCE"),
	PUR_ED ("Entry Date", "PUR.ED"),
	PUR_LCN ("Location", "PUR.LCN"),
	PUR_TAG ("Tag Location", "PUR.TAG"),
	PUR_COM ("Comment", "PUR.COM"),
	CNR_CNR ("Citation Number", "CNR.CNR"),
	CNR_CED ("Citation Entry Date", "CNR.CED"),
	CNR_CUPD ("Citation Update Date", "CNR.CUPD"),
	CIT_DT ("Document Type", "CIT.DT"),
	CIT_AU ("Authors", "CIT.AU"),
	CIT_PA ("Patent Assignee", "CIT.PA"),
	CIT_ABPR ("Abstract Presence", "CIT.ABPR"),
	CIT_IMPACT ("Impact Factor", "CIT.IMPACT"),
	CIT_PNX ("Common Patent Number", "CIT.PNX"),
	CIT_PREPY ("Preferred Publication Year", "CIT.PREPY"),
	CIT_PAGES ("Pages", "CIT.PAGES"),
	CIT_PUI ("PUI", "CIT.PUI"),
	CIT_PCC ("Patent Country Code", "CIT.PCC"),
	CIT_PN ("Patent Number", "CIT.PN"),
	CIT_PPY ("Patent Year", "CIT.PPY"),
	CIT_PK ("Patent Status", "CIT.PK"),
	CIT_PLA ("Patent Language Code", "CIT.PLA"),
	CIT_CO ("CODEN", "CIT.CO"),
	CIT_JT ("Journal Title", "CIT.JT"),
	CIT_JTS ("Journal Title (Short)", "CIT.JTS"),
	CIT_JTW ("Journal/Review Without CODEN", "CIT.JTW"),
	CIT_ISB ("ISBN", "CIT.ISB"),
	CIT_CC ("Country Code", "CIT.CC"),
	CIT_LA ("Language Code", "CIT.LA"),
	CIT_EDT ("Editor", "CIT.EDT"),
	CIT_PUB ("Publisher", "CIT.PUB"),
	CIT_LO ("Location of Publisher", "CIT.LO"),
	CIT_VL ("(Series) Volume", "CIT.VL"),
	CIT_NB ("Number", "CIT.NB"),
	CIT_PY ("Publication Year", "CIT.PY"),
	CIT_PAG ("Page", "CIT.PAG"),
	CIT_URES ("Citation (unresolved)", "CIT.URES"),
	CIT_DOI ("DOI", "CIT.DOI"),
	CIT_ARTNO ("Article Number", "CIT.ARTNO"),
	CIT_ISSN ("ISSN", "CIT.ISSN"),
	CIT_SCOPUS ("Scopus ID", "CIT.SCOPUS"),
	CIT_CITBY ("Cited By", "CIT.CITBY"),
	CIT_DOCQ ("Document Quality", "CIT.DOCQ"),
	CIT_HASBIO ("Bioactivity Presence", "CIT.HASBIO"),
	KWD_TYP ("Type", "KWD.TYP"),
	KWD_NAME ("Name", "KWD.NAME"),
	KWD_KW ("Keyword", "KWD.KW"),
	KWD_LINK ("Link", "KWD.LINK"),
	KWD_SUBLINK ("Sublink", "KWD.SUBLINK"),
	KWD_ONAME ("Object Name", "KWD.ONAME"),
	KWD_OID ("Object Identifier", "KWD.OID"),
	KWD_TRNAME ("Tradename", "KWD.TRNAME"),
	KWD_TRMANU ("Manufacturer", "KWD.TRMANU"),
	KWD_TRCTRY ("Country", "KWD.TRCTRY"),
	RXD_L ("Citation Pointer", "RXD.L"),
	RXD_SOURCE ("Source", "RXD.SOURCE"),
	RXD_CL ("Reaction Classification", "RXD.CL"),
	RXD_SCO ("Reaction Score", "RXD.SCO"),
	RXD_LB ("Example label", "RXD.LB"),
	RXD_TI ("Example title", "RXD.TI"),
	RXD_TXT ("Fulltext of reaction", "RXD.TXT"),
	RXD_STP ("Number of Reaction Steps", "RXD.STP"),
	RXD_MID ("Multi-step Scheme", "RXD.MID"),
	RXD_MTEXT ("Multi-step Details", "RXD.MTEXT"),
	RXD_YXRN ("Product XRN", "RXD.YXRN"),
	RXD_YPRO ("Product", "RXD.YPRO"),
	RXD_YD ("Yield", "RXD.YD"),
	RXD_NYD ("Yield (numerical)", "RXD.NYD"),
	RXD_YDO ("Yield (optical)", "RXD.YDO"),
	RXD_SNR ("Number of Stages", "RXD.SNR"),
	RXD_STG ("Stage Number", "RXD.STG"),
	RXD_SXRN ("Stage Reactant XRN", "RXD.SXRN"),
	RXD_SRCT ("Stage Reactant", "RXD.SRCT"),
	RXD_RGTXRN ("Reagent XRN", "RXD.RGTXRN"),
	RXD_RGT ("Reagent", "RXD.RGT"),
	RXD_CATXRN ("Catalyst XRN", "RXD.CATXRN"),
	RXD_CAT ("Catalyst", "RXD.CAT"),
	RXD_SOLXRN ("Solvent XRN", "RXD.SOLXRN"),
	RXD_SOL ("Solvent", "RXD.SOL"),
	RXD_RGTCAT ("Reagent/Catalyst", "RXD.RGTCAT"),
	RXD_SPH ("Solid Phase", "RXD.SPH"),
	RXD_TIM ("Time", "RXD.TIM"),
	RXD_T ("Temperature", "RXD.T"),
	RXD_P ("Pressure", "RXD.P"),
	RXD_PH ("pH-Value", "RXD.PH"),
	RXD_COND ("Other Conditions", "RXD.COND"),
	RXD_TYP ("Reaction Type", "RXD.TYP"),
	RXD_SUB ("Subject Studied", "RXD.SUB"),
	RXD_PRT ("Prototype Reaction", "RXD.PRT"),
	RXD_NAME ("Named Reaction", "RXD.NAME"),
	RXD_PARENTLINK ("Parent link", "RXD.PARENTLINK"),
	RXD_PARENTREF ("Parent reference", "RXD.PARENTREF"),
	RXD_RXDES ("Type of reaction description", "RXD.RXDES"),
	RXD_DED ("Entry Date", "RXD.DED"),
	RXD_LCN ("Location", "RXD.LCN"),
	RXD_TAG ("Tag Location", "RXD.TAG"),
	RXD_COM ("Comment", "RXD.COM"),
	DEN_L ("Citation Pointer", "DEN.L"),
	DEN_SOURCE ("Source", "DEN.SOURCE"),
	DEN_RT ("Reference Temperature", "DEN.RT"),
	DEN_T ("Measurement Temperature", "DEN.T"),
	DEN_TYP ("Type", "DEN.TYP"),
	DEN_ITYP ("Internal Type", "DEN.ITYP"),
	DEN_ED ("Entry Date", "DEN.ED"),
	DEN_LCN ("Location", "DEN.LCN"),
	DEN_TAG ("Tag Location", "DEN.TAG"),
	DEN_COM ("Comment", "DEN.COM"),
	CNF_L ("Citation Pointer", "CNF.L"),
	CNF_SOURCE ("Source", "CNF.SOURCE"),
	CNF_OBJ ("Object of Investigation", "CNF.OBJ"),
	CNF_ED ("Entry Date", "CNF.ED"),
	CNF_LCN ("Location", "CNF.LCN"),
	CNF_TAG ("Tag Location", "CNF.TAG"),
	CNF_COM ("Comment", "CNF.COM"),
	IDA_L ("Citation Pointer", "IDA.L"),
	IDA_SOURCE ("Source", "IDA.SOURCE"),
	IDA_KW ("Description", "IDA.KW"),
	IDA_ED ("Entry Date", "IDA.ED"),
	IDA_LCN ("Location", "IDA.LCN"),
	IDA_TAG ("Tag Location", "IDA.TAG"),
	IDA_COM ("Comment", "IDA.COM"),
	ELP_L ("Citation Pointer", "ELP.L"),
	ELP_SOURCE ("Source", "ELP.SOURCE"),
	ELP_KW ("Description", "ELP.KW"),
	ELP_ED ("Entry Date", "ELP.ED"),
	ELP_LCN ("Location", "ELP.LCN"),
	ELP_TAG ("Tag Location", "ELP.TAG"),
	ELP_COM ("Comment", "ELP.COM"),
	DFM_L ("Citation Pointer", "DFM.L"),
	DFM_SOURCE ("Source", "DFM.SOURCE"),
	DFM_KW ("Description", "DFM.KW"),
	DFM_ED ("Entry Date", "DFM.ED"),
	DFM_LCN ("Location", "DFM.LCN"),
	DFM_TAG ("Tag Location", "DFM.TAG"),
	DFM_COM ("Comment", "DFM.COM"),
	EBC_L ("Citation Pointer", "EBC.L"),
	EBC_SOURCE ("Source", "EBC.SOURCE"),
	EBC_TYP ("Barrier Type", "EBC.TYP"),
	EBC_SOL ("Solvent", "EBC.SOL"),
	EBC_ED ("Entry Date", "EBC.ED"),
	EBC_LCN ("Location", "EBC.LCN"),
	EBC_TAG ("Tag Location", "EBC.TAG"),
	EBC_COM ("Comment", "EBC.COM"),
	CIP_L ("Citation Pointer", "CIP.L"),
	CIP_SOURCE ("Source", "CIP.SOURCE"),
	CIP_KW ("Description", "CIP.KW"),
	CIP_ED ("Entry Date", "CIP.ED"),
	CIP_LCN ("Location", "CIP.LCN"),
	CIP_TAG ("Tag Location", "CIP.TAG"),
	CIP_COM ("Comment", "CIP.COM"),
	CPD_L ("Citation Pointer", "CPD.L"),
	CPD_SOURCE ("Source", "CPD.SOURCE"),
	CPD_PGROUP ("Point group", "CPD.PGROUP"),
	CPD_ED ("Entry Date", "CPD.ED"),
	CPD_LCN ("Location", "CPD.LCN"),
	CPD_TAG ("Tag Location", "CPD.TAG"),
	CPD_COM ("Comment", "CPD.COM"),
	CSG_L ("Citation Pointer", "CSG.L"),
	CSG_SOURCE ("Source", "CSG.SOURCE"),
	CSG_ED ("Entry Date", "CSG.ED"),
	CSG_LCN ("Location", "CSG.LCN"),
	CSG_TAG ("Tag Location", "CSG.TAG"),
	CSG_COM ("Comment", "CSG.COM"),
	CRT_L ("Citation Pointer", "CRT.L"),
	CRT_SOURCE ("Source", "CRT.SOURCE"),
	CRT_ED ("Entry Date", "CRT.ED"),
	CRT_LCN ("Location", "CRT.LCN"),
	CRT_TAG ("Tag Location", "CRT.TAG"),
	CRT_COM ("Comment", "CRT.COM"),
	CRP_L ("Citation Pointer", "CRP.L"),
	CRP_SOURCE ("Source", "CRP.SOURCE"),
	CRP_ED ("Entry Date", "CRP.ED"),
	CRP_LCN ("Location", "CRP.LCN"),
	CRP_TAG ("Tag Location", "CRP.TAG"),
	CRP_COM ("Comment", "CRP.COM"),
	CRD_L ("Citation Pointer", "CRD.L"),
	CRD_SOURCE ("Source", "CRD.SOURCE"),
	CRD_ED ("Entry Date", "CRD.ED"),
	CRD_LCN ("Location", "CRD.LCN"),
	CRD_TAG ("Tag Location", "CRD.TAG"),
	CRD_COM ("Comment", "CRD.COM"),
	CRV_L ("Citation Pointer", "CRV.L"),
	CRV_SOURCE ("Source", "CRV.SOURCE"),
	CRV_ED ("Entry Date", "CRV.ED"),
	CRV_LCN ("Location", "CRV.LCN"),
	CRV_TAG ("Tag Location", "CRV.TAG"),
	CRV_COM ("Comment", "CRV.COM"),
	MEC_L ("Citation Pointer", "MEC.L"),
	MEC_SOURCE ("Source", "MEC.SOURCE"),
	MEC_KW ("Description", "MEC.KW"),
	MEC_ED ("Entry Date", "MEC.ED"),
	MEC_LCN ("Location", "MEC.LCN"),
	MEC_TAG ("Tag Location", "MEC.TAG"),
	MEC_COM ("Comment", "MEC.COM"),
	HSP_L ("Citation Pointer", "HSP.L"),
	HSP_SOURCE ("Source", "HSP.SOURCE"),
	HSP_T ("Temperature", "HSP.T"),
	HSP_ED ("Entry Date", "HSP.ED"),
	HSP_LCN ("Location", "HSP.LCN"),
	HSP_TAG ("Tag Location", "HSP.TAG"),
	HSP_COM ("Comment", "HSP.COM"),
	CP0_L ("Citation Pointer", "CP0.L"),
	CP0_SOURCE ("Source", "CP0.SOURCE"),
	CP0_T ("Temperature", "CP0.T"),
	CP0_ED ("Entry Date", "CP0.ED"),
	CP0_LCN ("Location", "CP0.LCN"),
	CP0_TAG ("Tag Location", "CP0.TAG"),
	CP0_COM ("Comment", "CP0.COM"),
	OPT_L ("Citation Pointer", "OPT.L"),
	OPT_SOURCE ("Source", "OPT.SOURCE"),
	OPT_KW ("Description", "OPT.KW"),
	OPT_ED ("Entry Date", "OPT.ED"),
	OPT_LCN ("Location", "OPT.LCN"),
	OPT_TAG ("Tag Location", "OPT.TAG"),
	OPT_COM ("Comment", "OPT.COM"),
	ORP_L ("Citation Pointer", "ORP.L"),
	ORP_SOURCE ("Source", "ORP.SOURCE"),
	ORP_TYP ("Type", "ORP.TYP"),
	ORP_C ("Concentration", "ORP.C"),
	ORP_EE ("Enantiomeric excess", "ORP.EE"),
	ORP_LEN ("Length of Path", "ORP.LEN"),
	ORP_SOL ("Solvent", "ORP.SOL"),
	ORP_W ("Wavelength", "ORP.W"),
	ORP_T ("Temperature", "ORP.T"),
	ORP_ED ("Entry Date", "ORP.ED"),
	ORP_LCN ("Location", "ORP.LCN"),
	ORP_TAG ("Tag Location", "ORP.TAG"),
	ORP_COM ("Comment", "ORP.COM"),
	MUT_L ("Citation Pointer", "MUT.L"),
	MUT_SOURCE ("Source", "MUT.SOURCE"),
	MUT_TYP ("Type", "MUT.TYP"),
	MUT_C ("Concentration", "MUT.C"),
	MUT_LEN ("Length of Path", "MUT.LEN"),
	MUT_SOL ("Solvent", "MUT.SOL"),
	MUT_W ("Wavelength", "MUT.W"),
	MUT_T ("Temperature", "MUT.T"),
	MUT_TIM ("Time", "MUT.TIM"),
	MUT_ED ("Entry Date", "MUT.ED"),
	MUT_LCN ("Location", "MUT.LCN"),
	MUT_TAG ("Tag Location", "MUT.TAG"),
	MUT_COM ("Comment", "MUT.COM"),
	ORD_L ("Citation Pointer", "ORD.L"),
	ORD_SOURCE ("Source", "ORD.SOURCE"),
	ORD_SOL ("Solvent", "ORD.SOL"),
	ORD_ED ("Entry Date", "ORD.ED"),
	ORD_LCN ("Location", "ORD.LCN"),
	ORD_TAG ("Tag Location", "ORD.TAG"),
	ORD_COM ("Comment", "ORD.COM"),
	MAG_L ("Citation Pointer", "MAG.L"),
	MAG_SOURCE ("Source", "MAG.SOURCE"),
	MAG_KW ("Description", "MAG.KW"),
	MAG_T ("Temperature", "MAG.T"),
	MAG_MMOM ("Moment", "MAG.MMOM"),
	MAG_ED ("Entry Date", "MAG.ED"),
	MAG_LCN ("Location", "MAG.LCN"),
	MAG_TAG ("Tag Location", "MAG.TAG"),
	MAG_COM ("Comment", "MAG.COM"),
	DIC_L ("Citation Pointer", "DIC.L"),
	DIC_SOURCE ("Source", "DIC.SOURCE"),
	DIC_F ("Frequency", "DIC.F"),
	DIC_T ("Temperature", "DIC.T"),
	DIC_ED ("Entry Date", "DIC.ED"),
	DIC_LCN ("Location", "DIC.LCN"),
	DIC_TAG ("Tag Location", "DIC.TAG"),
	DIC_COM ("Comment", "DIC.COM"),
	ELE_L ("Citation Pointer", "ELE.L"),
	ELE_SOURCE ("Source", "ELE.SOURCE"),
	ELE_KW ("Description", "ELE.KW"),
	ELE_ECVAL ("Electric Conductivity", "ELE.ECVAL"),
	ELE_T ("Temperature of Electric Conductivity", "ELE.T"),
	ELE_CRIT ("Critical Superconductivity Temperature", "ELE.CRIT"),
	ELE_ED ("Entry Date", "ELE.ED"),
	ELE_LCN ("Location", "ELE.LCN"),
	ELE_TAG ("Tag Location", "ELE.TAG"),
	ELE_COM ("Comment", "ELE.COM"),
	IEP_L ("Citation Pointer", "IEP.L"),
	IEP_SOURCE ("Source", "IEP.SOURCE"),
	IEP_SOL ("Solvent", "IEP.SOL"),
	IEP_ED ("Entry Date", "IEP.ED"),
	IEP_LCN ("Location", "IEP.LCN"),
	IEP_TAG ("Tag Location", "IEP.TAG"),
	IEP_COM ("Comment", "IEP.COM"),
	POT_L ("Citation Pointer", "POT.L"),
	POT_SOURCE ("Source", "POT.SOURCE"),
	POT_KW ("Description", "POT.KW"),
	POT_SOL ("Solvent", "POT.SOL"),
	POT_PH ("pH-Value", "POT.PH"),
	POT_T ("Temperature", "POT.T"),
	POT_PXRN ("Product XRN", "POT.PXRN"),
	POT_PRO ("Product", "POT.PRO"),
	POT_ED ("Entry Date", "POT.ED"),
	POT_LCN ("Location", "POT.LCN"),
	POT_TAG ("Tag Location", "POT.TAG"),
	POT_COM ("Comment", "POT.COM"),
	SLB_L ("Citation Pointer", "SLB.L"),
	SLB_SOURCE ("Source", "SLB.SOURCE"),
	SLB_SAT ("Saturation", "SLB.SAT"),
	SLB_T ("Temperature", "SLB.T"),
	SLB_SOL ("Solvent", "SLB.SOL"),
	SLB_RAT ("Ratio of Solvents", "SLB.RAT"),
	SLB_ED ("Entry Date", "SLB.ED"),
	SLB_LCN ("Location", "SLB.LCN"),
	SLB_TAG ("Tag Location", "SLB.TAG"),
	SLB_COM ("Comment", "SLB.COM"),
	CMC_L ("Citation Pointer", "CMC.L"),
	CMC_SOURCE ("Source", "CMC.SOURCE"),
	CMC_T ("Temperature", "CMC.T"),
	CMC_SOL ("Solvent", "CMC.SOL"),
	CMC_ED ("Entry Date", "CMC.ED"),
	CMC_LCN ("Location", "CMC.LCN"),
	CMC_TAG ("Tag Location", "CMC.TAG"),
	CMC_COM ("Comment", "CMC.COM"),
	HEN_L ("Citation Pointer", "HEN.L"),
	HEN_SOURCE ("Source", "HEN.SOURCE"),
	HEN_LOG ("log Henry Constant", "HEN.LOG"),
	HEN_T ("Temperature", "HEN.T"),
	HEN_SOL ("Solvent", "HEN.SOL"),
	HEN_ED ("Entry Date", "HEN.ED"),
	HEN_LCN ("Location", "HEN.LCN"),
	HEN_TAG ("Tag Location", "HEN.TAG"),
	HEN_COM ("Comment", "HEN.COM"),
	POW_L ("Citation Pointer", "POW.L"),
	POW_SOURCE ("Source", "POW.SOURCE"),
	POW_LOG ("log POW", "POW.LOG"),
	POW_T ("Temperature", "POW.T"),
	POW_PH ("pH", "POW.PH"),
	POW_ED ("Entry Date", "POW.ED"),
	POW_LCN ("Location", "POW.LCN"),
	POW_TAG ("Tag Location", "POW.TAG"),
	POW_COM ("Comment", "POW.COM"),
	AZE_L ("Citation Pointer", "AZE.L"),
	AZE_SOURCE ("Source", "AZE.SOURCE"),
	AZE_PB ("Azeotropes XRN", "AZE.PB"),
	AZE_PA ("Azeotropes", "AZE.PA"),
	AZE_T ("Temperature", "AZE.T"),
	AZE_P ("Pressure", "AZE.P"),
	AZE_C ("Concentrations", "AZE.C"),
	AZE_ED ("Entry Date", "AZE.ED"),
	AZE_LCN ("Location", "AZE.LCN"),
	AZE_TAG ("Tag Location", "AZE.TAG"),
	AZE_COM ("Comment", "AZE.COM"),
	EDM_L ("Citation Pointer", "EDM.L"),
	EDM_SOURCE ("Source", "EDM.SOURCE"),
	EDM_KW ("Description", "EDM.KW"),
	EDM_PB ("Partner XRN", "EDM.PB"),
	EDM_PA ("Partner", "EDM.PA"),
	EDM_SOL ("Solvent", "EDM.SOL"),
	EDM_T ("Temperature", "EDM.T"),
	EDM_P ("Pressure", "EDM.P"),
	EDM_ED ("Entry Date", "EDM.ED"),
	EDM_LCN ("Location", "EDM.LCN"),
	EDM_TAG ("Tag Location", "EDM.TAG"),
	EDM_COM ("Comment", "EDM.COM"),
	ODM_L ("Citation Pointer", "ODM.L"),
	ODM_SOURCE ("Source", "ODM.SOURCE"),
	ODM_KW ("Description", "ODM.KW"),
	ODM_PB ("Partner XRN", "ODM.PB"),
	ODM_PA ("Partner", "ODM.PA"),
	ODM_SOL ("Solvent", "ODM.SOL"),
	ODM_T ("Temperature", "ODM.T"),
	ODM_P ("Pressure", "ODM.P"),
	ODM_ED ("Entry Date", "ODM.ED"),
	ODM_LCN ("Location", "ODM.LCN"),
	ODM_TAG ("Tag Location", "ODM.TAG"),
	ODM_COM ("Comment", "ODM.COM"),
	NMR_L ("Citation Pointer", "NMR.L"),
	NMR_SOURCE ("Source", "NMR.SOURCE"),
	NMR_KW ("Description", "NMR.KW"),
	NMR_NUC ("Nucleus", "NMR.NUC"),
	NMR_NUI ("Coupling Nuclei", "NMR.NUI"),
	NMR_SOL ("Solvents", "NMR.SOL"),
	NMR_T ("Temperature", "NMR.T"),
	NMR_F ("Frequency", "NMR.F"),
	NMR_TXT ("Original Text", "NMR.TXT"),
	NMR_SIG ("Signals", "NMR.SIG"),
	NMR_SIGTYP ("Kind of signal", "NMR.SIGTYP"),
	NMR_INT ("Intensity", "NMR.INT"),
	NMR_ED ("Entry Date", "NMR.ED"),
	NMR_LCN ("Location", "NMR.LCN"),
	NMR_TAG ("Tag Location", "NMR.TAG"),
	NMR_COM ("Comment", "NMR.COM"),
	ESR_L ("Citation Pointer", "ESR.L"),
	ESR_SOURCE ("Source", "ESR.SOURCE"),
	ESR_KW ("Description", "ESR.KW"),
	ESR_NUI ("Coupling Nuclei", "ESR.NUI"),
	ESR_SOL ("Solvents", "ESR.SOL"),
	ESR_T ("Temperature", "ESR.T"),
	ESR_ED ("Entry Date", "ESR.ED"),
	ESR_LCN ("Location", "ESR.LCN"),
	ESR_TAG ("Tag Location", "ESR.TAG"),
	ESR_COM ("Comment", "ESR.COM"),
	NQR_L ("Citation Pointer", "NQR.L"),
	NQR_SOURCE ("Source", "NQR.SOURCE"),
	NQR_KW ("Description", "NQR.KW"),
	NQR_NUC ("Nucleus", "NQR.NUC"),
	NQR_ED ("Entry Date", "NQR.ED"),
	NQR_LCN ("Location", "NQR.LCN"),
	NQR_TAG ("Tag Location", "NQR.TAG"),
	NQR_COM ("Comment", "NQR.COM"),
	ROT_L ("Citation Pointer", "ROT.L"),
	ROT_SOURCE ("Source", "ROT.SOURCE"),
	ROT_KW ("Description", "ROT.KW"),
	ROT_ED ("Entry Date", "ROT.ED"),
	ROT_LCN ("Location", "ROT.LCN"),
	ROT_TAG ("Tag Location", "ROT.TAG"),
	ROT_COM ("Comment", "ROT.COM"),
	LUM_L ("Citation Pointer", "LUM.L"),
	LUM_SOURCE ("Source", "LUM.SOURCE"),
	LUM_KW ("Description", "LUM.KW"),
	LUM_ED ("Entry Date", "LUM.ED"),
	LUM_LCN ("Location", "LUM.LCN"),
	LUM_TAG ("Tag Location", "LUM.TAG"),
	LUM_COM ("Comment", "LUM.COM"),
	FLU_L ("Citation Pointer", "FLU.L"),
	FLU_SOURCE ("Source", "FLU.SOURCE"),
	FLU_KW ("Description", "FLU.KW"),
	FLU_SOL ("Solvent", "FLU.SOL"),
	FLU_T ("Temperature", "FLU.T"),
	FLU_ED ("Entry Date", "FLU.ED"),
	FLU_LCN ("Location", "FLU.LCN"),
	FLU_TAG ("Tag Location", "FLU.TAG"),
	FLU_COM ("Comment", "FLU.COM"),
	PHO_L ("Citation Pointer", "PHO.L"),
	PHO_SOURCE ("Source", "PHO.SOURCE"),
	PHO_KW ("Description", "PHO.KW"),
	PHO_SOL ("Solvent", "PHO.SOL"),
	PHO_T ("Temperature", "PHO.T"),
	PHO_ED ("Entry Date", "PHO.ED"),
	PHO_LCN ("Location", "PHO.LCN"),
	PHO_TAG ("Tag Location", "PHO.TAG"),
	PHO_COM ("Comment", "PHO.COM"),
	OSM_L ("Citation Pointer", "OSM.L"),
	OSM_SOURCE ("Source", "OSM.SOURCE"),
	OSM_KW ("Description", "OSM.KW"),
	OSM_MOENUC ("Nucleus", "OSM.MOENUC"),
	OSM_ED ("Entry Date", "OSM.ED"),
	OSM_LCN ("Location", "OSM.LCN"),
	OSM_TAG ("Tag Location", "OSM.TAG"),
	OSM_COM ("Comment", "OSM.COM"),
	ECT_L ("Citation Pointer", "ECT.L"),
	ECT_SOURCE ("Source", "ECT.SOURCE"),
	ECT_E ("Effect", "ECT.E"),
	ECT_EP ("Endpoint of Effect", "ECT.EP"),
	ECT_SP ("Species or Test-System", "ECT.SP"),
	ECT_S ("Sex", "ECT.S"),
	ECT_RA ("Route of Application", "ECT.RA"),
	ECT_C ("Concentration", "ECT.C"),
	ECT_KD ("Kind of Dosing", "ECT.KD"),
	ECT_EX ("Exposure Period", "ECT.EX"),
	ECT_MR ("Method", "ECT.MR"),
	ECT_FD ("Further Details", "ECT.FD"),
	ECT_TY ("Type", "ECT.TY"),
	ECT_V ("Value of Type", "ECT.V"),
	ECT_RE ("Results", "ECT.RE"),
	ECT_XRN ("Metabolite XRN", "ECT.XRN"),
	ECT_META ("Metabolite", "ECT.META"),
	ECT_ED ("Entry Date", "ECT.ED"),
	ECT_LCN ("Location", "ECT.LCN"),
	ECT_TAG ("Tag Location", "ECT.TAG"),
	ECT_COM ("Comment", "ECT.COM"),
	ECA_L ("Citation Pointer", "ECA.L"),
	ECA_SOURCE ("Source", "ECA.SOURCE"),
	ECA_HE ("Exposure", "ECA.HE"),
	ECA_SO ("Sources", "ECA.SO"),
	ECA_ED ("Entry Date", "ECA.ED"),
	ECA_LCN ("Location", "ECA.LCN"),
	ECA_TAG ("Tag Location", "ECA.TAG"),
	ECA_COM ("Comment", "ECA.COM"),
	ECC_L ("Citation Pointer", "ECC.L"),
	ECC_SOURCE ("Source", "ECC.SOURCE"),
	ECC_SP ("Species", "ECC.SP"),
	ECC_ME ("Media", "ECC.ME"),
	ECC_LO ("Location", "ECC.LO"),
	ECC_CC ("Contamination Concentration", "ECC.CC"),
	ECC_BC ("Background Concentration", "ECC.BC"),
	ECC_MR ("Method, Remarks", "ECC.MR"),
	ECC_ED ("Entry Date", "ECC.ED"),
	ECC_LCN ("Location", "ECC.LCN"),
	ECC_TAG ("Tag Location", "ECC.TAG"),
	ECC_COM ("Comment", "ECC.COM"),
	BIO_L ("Citation Pointer", "BIO.L"),
	BIO_SOURCE ("Source", "BIO.SOURCE"),
	BIO_SP ("Species", "BIO.SP"),
	BIO_ME ("Media", "BIO.ME"),
	BIO_C ("Concentration", "BIO.C"),
	BIO_E ("Exposure Period", "BIO.E"),
	BIO_T ("Temperature", "BIO.T"),
	BIO_BC ("Bioconcentration Factor (BCF)", "BIO.BC"),
	BIO_LOG ("log BCF ", "BIO.LOG"),
	BIO_A ("Accumulation Half-life Time", "BIO.A"),
	BIO_AR ("Accumulation Rate Constant", "BIO.AR"),
	BIO_H ("Elimination Half-life Time", "BIO.H"),
	BIO_ER ("Elimination Rate Constant", "BIO.ER"),
	BIO_MR ("Method, Remarks", "BIO.MR"),
	BIO_MAG ("Biomagnification", "BIO.MAG"),
	BIO_MON ("Biomonitoring", "BIO.MON"),
	BIO_ED ("Entry Date", "BIO.ED"),
	BIO_LCN ("Location", "BIO.LCN"),
	BIO_TAG ("Tag Location", "BIO.TAG"),
	BIO_COM ("Comment", "BIO.COM"),
	ECS_L ("Citation Pointer", "ECS.L"),
	ECS_SOURCE ("Source", "ECS.SOURCE"),
	ECS_TY ("Type", "ECS.TY"),
	ECS_C ("Concentration", "ECS.C"),
	ECS_5 ("Dissipation Time 50", "ECS.5"),
	ECS_9 ("Dissipation Time 90", "ECS.9"),
	ECS_D ("Dissipation", "ECS.D"),
	ECS_E ("Exposure Period", "ECS.E"),
	ECS_T ("Temperature", "ECS.T"),
	ECS_PH ("pH-Value", "ECS.PH"),
	ECS_HU ("Humidity", "ECS.HU"),
	ECS_OC ("Organic Carbon", "ECS.OC"),
	ECS_CE ("Cation Exchange Rate", "ECS.CE"),
	ECS_MB ("Microbial Biomass", "ECS.MB"),
	ECS_MR ("Method, Remarks", "ECS.MR"),
	ECS_ED ("Entry Date", "ECS.ED"),
	ECS_LCN ("Location", "ECS.LCN"),
	ECS_TAG ("Tag Location", "ECS.TAG"),
	ECS_COM ("Comment", "ECS.COM"),
	EOD_L ("Citation Pointer", "EOD.L"),
	EOD_SOURCE ("Source", "EOD.SOURCE"),
	EOD_TY ("Type", "EOD.TY"),
	EOD_RE ("Related to", "EOD.RE"),
	EOD_C ("Concentration", "EOD.C"),
	EOD_D ("Oxygen Demand", "EOD.D"),
	EOD_RAT ("Ratio BOD5/COD", "EOD.RAT"),
	EOD_MR ("Method, Remarks", "EOD.MR"),
	EOD_ED ("Entry Date", "EOD.ED"),
	EOD_LCN ("Location", "EOD.LCN"),
	EOD_TAG ("Tag Location", "EOD.TAG"),
	EOD_COM ("Comment", "EOD.COM"),
	USE_L ("Citation Pointer", "USE.L"),
	USE_SOURCE ("Source", "USE.SOURCE"),
	USE_LH ("Laboratory Use and Handling", "USE.LH"),
	USE_PT ("Use Pattern", "USE.PT"),
	USE_ED ("Entry Date", "USE.ED"),
	USE_LCN ("Location", "USE.LCN"),
	USE_TAG ("Tag Location", "USE.TAG"),
	USE_COM ("Comment", "USE.COM"),
	INP_L ("Citation Pointer", "INP.L"),
	INP_SOURCE ("Source", "INP.SOURCE"),
	INP_ED ("Entry Date", "INP.ED"),
	INP_LCN ("Location", "INP.LCN"),
	INP_TAG ("Tag Location", "INP.TAG"),
	INP_COM ("Comment", "INP.COM"),
	DAT_ID ("Data Point ID", "DAT.ID"),
	DAT_CIT ("Citation Pointer", "DAT.CIT"),
	DAT_SRC ("Source", "DAT.SRC"),
	DAT_CID ("Substance Table ID", "DAT.CID"),
	DAT_CTYPE ("Substance Type", "DAT.CTYPE"),
	DAT_MRN ("Substance RN", "DAT.MRN"),
	DAT_MNAME ("Substance Name", "DAT.MNAME"),
	DAT_MROUTE ("Substance Route", "DAT.MROUTE"),
	DAT_MREGIM ("Substance Dosing", "DAT.MREGIM"),
	DAT_MDOSE ("Substance Dose", "DAT.MDOSE"),
	DAT_CLPHASE ("Highest Clinical Phase", "DAT.CLPHASE"),
	DAT_SRN ("Substrate RN", "DAT.SRN"),
	DAT_SNAME ("Substrate Name", "DAT.SNAME"),
	DAT_MID ("Measurement ID", "DAT.MID"),
	DAT_VTYPE ("Parameter", "DAT.VTYPE"),
	DAT_VLIMIT ("Value Threshold", "DAT.VLIMIT"),
	DAT_AID ("Bioassay ID", "DAT.AID"),
	DAT_ANAME ("Bioassay Name", "DAT.ANAME"),
	DAT_AFTYPE ("Bioassay Full Type", "DAT.AFTYPE"),
	DAT_CATEG ("Bioassay Category", "DAT.CATEG"),
	DAT_MODEL ("Animal Model", "DAT.MODEL"),
	DAT_PATHO ("Population", "DAT.PATHO"),
	DAT_ACTTRG ("Putative action on target", "DAT.ACTTRG"),
	DAT_ADESC ("Bioassay Description", "DAT.ADESC"),
	DAT_EFFECT ("Effect", "DAT.EFFECT"),
	DAT_BID ("Biological Material ID", "DAT.BID"),
	DAT_BNAME ("Biological Material Name", "DAT.BNAME"),
	DAT_BCELL ("Cells-Cell lines", "DAT.BCELL"),
	DAT_BPART ("Cell Fraction", "DAT.BPART"),
	DAT_BTISSUE ("Organs/Tissues", "DAT.BTISSUE"),
	DAT_BSTRAIN ("Strain", "DAT.BSTRAIN"),
	DAT_BSTATE ("State", "DAT.BSTATE"),
	DAT_BSPECIE ("Biological Species", "DAT.BSPECIE"),
	DAT_TID ("Target ID", "DAT.TID"),
	DAT_TNAME ("Target Name", "DAT.TNAME"),
	DAT_TSUBUNIT ("Target Subunit Names", "DAT.TSUBUNIT"),
	DAT_TABBR ("Target Abbreviation", "DAT.TABBR"),
	DAT_TSYNON ("Target Synonyms", "DAT.TSYNON"),
	DAT_TSUBSYN ("Target Subunit Synonyms", "DAT.TSUBSYN"),
	DAT_TSPECIE ("Target Species", "DAT.TSPECIE"),
	DAT_TNATURE ("Target Nature", "DAT.TNATURE"),
	DAT_TCLASS ("Target Class", "DAT.TCLASS"),
	DAT_TDETAILS ("Target Mutant-Chimera Details", "DAT.TDETAILS"),
	DAT_TGENETREE ("Target Genetree", "DAT.TGENETREE"),
	DAT_TUNIPROT ("Target Uniprot", "DAT.TUNIPROT"),
	DAT_TPDB ("Target PDB", "DAT.TPDB"),
	DAT_TKEY ("Target Key", "DAT.TKEY"),
	DAT_TSKEY ("Target Short Key", "DAT.TSKEY"),
	DAT_TROLE ("Target Role", "DAT.TROLE"),
	DAT_TTRANSFECT ("Transfection", "DAT.TTRANSFECT"),
	DAT_ASPECIE ("Species", "DAT.ASPECIE"),
	DAT_CTL ("Control Point ID", "DAT.CTL"),
	DAT_CFLAG ("Control Point Flag", "DAT.CFLAG"),
	DAT_TEXT ("Results", "DAT.TEXT"),
	DAT_EXACT ("value (qual)", "DAT.EXACT"),
	DAT_VALUE ("value (quant)", "DAT.VALUE"),
	DAT_DEV ("value (dev)", "DAT.DEV"),
	DAT_UNIT ("unit", "DAT.UNIT"),
	DAT_PAUREUS ("pX", "DAT.PAUREUS"),
	DAT_PRANGES ("pX Ranges", "DAT.PRANGES"),
	DAT_PAUORIG ("pX Origin", "DAT.PAUORIG"),
	DAT_SIGNIF ("significance", "DAT.SIGNIF"),
	DAT_PVALUE ("p value", "DAT.PVALUE"),
	DAT_MCOUNT ("measurement count", "DAT.MCOUNT"),
	LIGO_BASE ("Base Formula", "LIGO.BASE"),
	LIGO_FORM ("Formula", "LIGO.FORM"),
	LIGO_CNT ("Count", "LIGO.CNT"),
	LIGM_BASE ("Base Formula", "LIGM.BASE"),
	LIGM_FORM ("Formula", "LIGM.FORM"),
	LIGM_CNT ("Count", "LIGM.CNT"),
	CALC_LOGP ("LogP", "CALC.LOGP"),
	CALC_HDONOR ("H Bond Donors", "CALC.HDONOR"),
	CALC_HACCOR ("H Bond Acceptors", "CALC.HACCOR"),
	CALC_ROTBND ("Rotatable Bonds", "CALC.ROTBND"),
	CALC_TPSA ("TPSA", "CALC.TPSA"),
	CALC_LIPINSKI ("Lipinski Number", "CALC.LIPINSKI"),
	CALC_VEBER ("Veber Number", "CALC.VEBER"),
	RSTR_L ("Citation Pointer", "RSTR.L"),
	RSTR_SOURCE ("Source", "RSTR.SOURCE"),
	RSTR_PB ("Referenced XRN", "RSTR.PB"),
	RSTR_PA ("Referenced Compound", "RSTR.PA"),
	RSTR_ED ("Entry Date", "RSTR.ED"),
	RSTR_LCN ("Location", "RSTR.LCN"),
	RSTR_TAG ("Tag Location", "RSTR.TAG"),
	RSTR_COM ("Comment", "RSTR.COM"),
	CDER_L ("Citation Pointer", "CDER.L"),
	CDER_SOURCE ("Source", "CDER.SOURCE"),
	CDER_XRN ("Derivative XRN", "CDER.XRN"),
	CDER_MP ("Derivative Melting Point", "CDER.MP"),
	CDER_ED ("Entry Date", "CDER.ED"),
	CDER_LCN ("Location", "CDER.LCN"),
	CDER_TAG ("Tag Location", "CDER.TAG"),
	CDER_COM ("Comment", "CDER.COM"),
	PBIB_PD ("Date of publication", "PBIB.PD"),
	PBIB_AP ("Application number", "PBIB.AP"),
	PBIB_FD ("Date of filing", "PBIB.FD"),
	PBIB_MAN ("Manually excerpted", "PBIB.MAN"),
	PBIB_INV ("Inventor", "PBIB.INV"),
	PBIB_PRNR ("Priority number", "PBIB.PRNR"),
	PBIB_PRD ("Priority date", "PBIB.PRD"),
	PBIB_ICM ("Main IPC", "PBIB.ICM"),
	PBIB_ICS ("Secondary IPC", "PBIB.ICS"),
	PBIB_CLAIMS ("Claims", "PBIB.CLAIMS"),
	PBIB_FPN ("Family member: Patent number", "PBIB.FPN"),
	PBIB_FPSTAT ("Family member: Status code", "PBIB.FPSTAT"),
	PBIB_FPD ("Family member: Date of publication", "PBIB.FPD"),
	PBIB_FAP ("Family member: Application number", "PBIB.FAP"),
	PBIB_FFD ("Family member: Date of filing", "PBIB.FFD"),
	PBIB_FIDX ("Family member: Indexed patent", "PBIB.FIDX"),
	EDIS_L ("Citation Pointer", "EDIS.L"),
	EDIS_SOURCE ("Source", "EDIS.SOURCE"),
	EDIS_TYP ("Bond Type", "EDIS.TYP"),
	EDIS_ED ("Entry Date", "EDIS.ED"),
	EDIS_LCN ("Location", "EDIS.LCN"),
	EDIS_TAG ("Tag Location", "EDIS.TAG"),
	EDIS_COM ("Comment", "EDIS.COM"),
	CPTP_L ("Citation Pointer", "CPTP.L"),
	CPTP_SOURCE ("Source", "CPTP.SOURCE"),
	CPTP_CM ("Change of Modification", "CPTP.CM"),
	CPTP_ED ("Entry Date", "CPTP.ED"),
	CPTP_LCN ("Location", "CPTP.LCN"),
	CPTP_TAG ("Tag Location", "CPTP.TAG"),
	CPTP_COM ("Comment", "CPTP.COM"),
	CSYS_L ("Citation Pointer", "CSYS.L"),
	CSYS_SOURCE ("Source", "CSYS.SOURCE"),
	CSYS_ED ("Entry Date", "CSYS.ED"),
	CSYS_LCN ("Location", "CSYS.LCN"),
	CSYS_TAG ("Tag Location", "CSYS.TAG"),
	CSYS_COM ("Comment", "CSYS.COM"),
	CDEN_L ("Citation Pointer", "CDEN.L"),
	CDEN_SOURCE ("Source", "CDEN.SOURCE"),
	CDEN_T ("Temperature", "CDEN.T"),
	CDEN_ITYP ("Internal Type", "CDEN.ITYP"),
	CDEN_ED ("Entry Date", "CDEN.ED"),
	CDEN_LCN ("Location", "CDEN.LCN"),
	CDEN_TAG ("Tag Location", "CDEN.TAG"),
	CDEN_COM ("Comment", "CDEN.COM"),
	LPTP_L ("Citation Pointer", "LPTP.L"),
	LPTP_SOURCE ("Source", "LPTP.SOURCE"),
	LPTP_CM ("Change of Modification", "LPTP.CM"),
	LPTP_ED ("Entry Date", "LPTP.ED"),
	LPTP_LCN ("Location", "LPTP.LCN"),
	LPTP_TAG ("Tag Location", "LPTP.TAG"),
	LPTP_COM ("Comment", "LPTP.COM"),
	COMP_L ("Citation Pointer", "COMP.L"),
	COMP_SOURCE ("Source", "COMP.SOURCE"),
	COMP_KW ("Description", "COMP.KW"),
	COMP_ED ("Entry Date", "COMP.ED"),
	COMP_LCN ("Location", "COMP.LCN"),
	COMP_TAG ("Tag Location", "COMP.TAG"),
	COMP_COM ("Comment", "COMP.COM"),
	SDIF_L ("Citation Pointer", "SDIF.L"),
	SDIF_SOURCE ("Source", "SDIF.SOURCE"),
	SDIF_T ("Temperature", "SDIF.T"),
	SDIF_ED ("Entry Date", "SDIF.ED"),
	SDIF_LCN ("Location", "SDIF.LCN"),
	SDIF_TAG ("Tag Location", "SDIF.TAG"),
	TEXP_L ("Citation Pointer", "TEXP.L"),
	TEXP_SOURCE ("Source", "TEXP.SOURCE"),
	TEXP_VAL ("Coefficient", "TEXP.VAL"),
	TEXP_LEC ("Kind of Expansion", "TEXP.LEC"),
	TEXP_T ("Temperature", "TEXP.T"),
	TEXP_ED ("Entry Date", "TEXP.ED"),
	TEXP_LCN ("Location", "TEXP.LCN"),
	TEXP_TAG ("Tag Location", "TEXP.TAG"),
	TEXP_COM ("Comment", "TEXP.COM"),
	HCOM_L ("Citation Pointer", "HCOM.L"),
	HCOM_SOURCE ("Source", "HCOM.SOURCE"),
	HCOM_T ("Temperature", "HCOM.T"),
	HCOM_P ("Pressure", "HCOM.P"),
	HCOM_ED ("Entry Date", "HCOM.ED"),
	HCOM_LCN ("Location", "HCOM.LCN"),
	HCOM_TAG ("Tag Location", "HCOM.TAG"),
	HCOM_COM ("Comment", "HCOM.COM"),
	HFOR_L ("Citation Pointer", "HFOR.L"),
	HFOR_SOURCE ("Source", "HFOR.SOURCE"),
	HFOR_T ("Temperature", "HFOR.T"),
	HFOR_P ("Pressure", "HFOR.P"),
	HFOR_ED ("Entry Date", "HFOR.ED"),
	HFOR_LCN ("Location", "HFOR.LCN"),
	HFOR_TAG ("Tag Location", "HFOR.TAG"),
	HFOR_COM ("Comment", "HFOR.COM"),
	HHDG_L ("Citation Pointer", "HHDG.L"),
	HHDG_SOURCE ("Source", "HHDG.SOURCE"),
	HHDG_XRN ("Product XRN", "HHDG.XRN"),
	HHDG_CN ("Product Name", "HHDG.CN"),
	HHDG_T ("Temperature", "HHDG.T"),
	HHDG_ED ("Entry Date", "HHDG.ED"),
	HHDG_LCN ("Location", "HHDG.LCN"),
	HHDG_TAG ("Tag Location", "HHDG.TAG"),
	HHDG_COM ("Comment", "HHDG.COM"),
	HFUS_L ("Citation Pointer", "HFUS.L"),
	HFUS_SOURCE ("Source", "HFUS.SOURCE"),
	HFUS_ED ("Entry Date", "HFUS.ED"),
	HFUS_LCN ("Location", "HFUS.LCN"),
	HFUS_TAG ("Tag Location", "HFUS.TAG"),
	HFUS_COM ("Comment", "HFUS.COM"),
	HVAP_L ("Citation Pointer", "HVAP.L"),
	HVAP_SOURCE ("Source", "HVAP.SOURCE"),
	HVAP_T ("Temperature", "HVAP.T"),
	HVAP_P ("Pressure", "HVAP.P"),
	HVAP_ED ("Entry Date", "HVAP.ED"),
	HVAP_LCN ("Location", "HVAP.LCN"),
	HVAP_TAG ("Tag Location", "HVAP.TAG"),
	HVAP_COM ("Comment", "HVAP.COM"),
	HPTP_L ("Citation Pointer", "HPTP.L"),
	HPTP_SOURCE ("Source", "HPTP.SOURCE"),
	HPTP_ED ("Entry Date", "HPTP.ED"),
	HPTP_LCN ("Location", "HPTP.LCN"),
	HPTP_TAG ("Tag Location", "HPTP.TAG"),
	HPTP_COM ("Comment", "HPTP.COM"),
	OTHE_L ("Citation Pointer", "OTHE.L"),
	OTHE_SOURCE ("Source", "OTHE.SOURCE"),
	OTHE_KW ("Description", "OTHE.KW"),
	OTHE_ED ("Entry Date", "OTHE.ED"),
	OTHE_LCN ("Location", "OTHE.LCN"),
	OTHE_TAG ("Tag Location", "OTHE.TAG"),
	OTHE_COM ("Comment", "OTHE.COM"),
	CDIC_L ("Citation Pointer", "CDIC.L"),
	CDIC_SOURCE ("Source", "CDIC.SOURCE"),
	CDIC_SOL ("Solvent", "CDIC.SOL"),
	CDIC_ED ("Entry Date", "CDIC.ED"),
	CDIC_LCN ("Location", "CDIC.LCN"),
	CDIC_TAG ("Tag Location", "CDIC.TAG"),
	CDIC_COM ("Comment", "CDIC.COM"),
	MSUS_L ("Citation Pointer", "MSUS.L"),
	MSUS_SOURCE ("Source", "MSUS.SOURCE"),
	MSUS_T ("Temperature", "MSUS.T"),
	MSUS_ED ("Entry Date", "MSUS.ED"),
	MSUS_LCN ("Location", "MSUS.LCN"),
	MSUS_TAG ("Tag Location", "MSUS.TAG"),
	MSUS_COM ("Comment", "MSUS.COM"),
	SDIC_L ("Citation Pointer", "SDIC.L"),
	SDIC_SOURCE ("Source", "SDIC.SOURCE"),
	SDIC_T ("Temperature", "SDIC.T"),
	SDIC_ED ("Entry Date", "SDIC.ED"),
	SDIC_LCN ("Location", "SDIC.LCN"),
	SDIC_TAG ("Tag Location", "SDIC.TAG"),
	SDIC_COM ("Comment", "SDIC.COM"),
	ELCB_L ("Citation Pointer", "ELCB.L"),
	ELCB_SOURCE ("Source", "ELCB.SOURCE"),
	ELCB_KW ("Description", "ELCB.KW"),
	ELCB_ED ("Entry Date", "ELCB.ED"),
	ELCB_LCN ("Location", "ELCB.LCN"),
	ELCB_TAG ("Tag Location", "ELCB.TAG"),
	ELCB_COM ("Comment", "ELCB.COM"),
	ELYC_L ("Citation Pointer", "ELYC.L"),
	ELYC_SOURCE ("Source", "ELYC.SOURCE"),
	ELYC_KW ("Description", "ELYC.KW"),
	ELYC_VAL ("Electrolytic Conductivity", "ELYC.VAL"),
	ELYC_AEVAL ("Equivalent Conductivity", "ELYC.AEVAL"),
	ELYC_T ("Temperature", "ELYC.T"),
	ELYC_SOL ("Solvent", "ELYC.SOL"),
	ELYC_REM ("Kind of Conductivity", "ELYC.REM"),
	ELYC_ED ("Entry Date", "ELYC.ED"),
	ELYC_LCN ("Location", "ELYC.LCN"),
	ELYC_TAG ("Tag Location", "ELYC.TAG"),
	ELYC_COM ("Comment", "ELYC.COM"),
	ELCH_L ("Citation Pointer", "ELCH.L"),
	ELCH_SOURCE ("Source", "ELCH.SOURCE"),
	ELCH_DESCR ("Electrochemical Cell", "ELCH.DESCR"),
	ELCH_POT ("Cell Potential", "ELCH.POT"),
	ELCH_KW ("Description", "ELCH.KW"),
	ELCH_ED ("Entry Date", "ELCH.ED"),
	ELCH_LCN ("Location", "ELCH.LCN"),
	ELCH_TAG ("Tag Location", "ELCH.TAG"),
	ELCH_COM ("Comment", "ELCH.COM"),
	FLAP_L ("Citation Pointer", "FLAP.L"),
	FLAP_SOURCE ("Source", "FLAP.SOURCE"),
	FLAP_TYP ("Type of Test", "FLAP.TYP"),
	FLAP_ED ("Entry Date", "FLAP.ED"),
	FLAP_LCN ("Location", "FLAP.LCN"),
	FLAP_TAG ("Tag Location", "FLAP.TAG"),
	FLAP_COM ("Comment", "FLAP.COM"),
	AUTI_L ("Citation Pointer", "AUTI.L"),
	AUTI_SOURCE ("Source", "AUTI.SOURCE"),
	AUTI_T ("Temperature", "AUTI.T"),
	AUTI_ED ("Entry Date", "AUTI.ED"),
	AUTI_LCN ("Location", "AUTI.LCN"),
	AUTI_TAG ("Tag Location", "AUTI.TAG"),
	AUTI_COM ("Comment", "AUTI.COM"),
	EXPL_L ("Citation Pointer", "EXPL.L"),
	EXPL_SOURCE ("Source", "EXPL.SOURCE"),
	EXPL_LV ("Explosion Limit", "EXPL.LV"),
	EXPL_ED ("Entry Date", "EXPL.ED"),
	EXPL_LCN ("Location", "EXPL.LCN"),
	EXPL_TAG ("Tag Location", "EXPL.TAG"),
	EXPL_COM ("Comment", "EXPL.COM"),
	SLBP_L ("Citation Pointer", "SLBP.L"),
	SLBP_SOURCE ("Source", "SLBP.SOURCE"),
	SLBP_T ("Temperature", "SLBP.T"),
	SLBP_SOL ("Solvent", "SLBP.SOL"),
	SLBP_RAT ("Ratio of Solvents", "SLBP.RAT"),
	SLBP_ED ("Entry Date", "SLBP.ED"),
	SLBP_LCN ("Location", "SLBP.LCN"),
	SLBP_TAG ("Tag Location", "SLBP.TAG"),
	SLBP_COM ("Comment", "SLBP.COM"),
	SOLM_L ("Citation Pointer", "SOLM.L"),
	SOLM_SOURCE ("Source", "SOLM.SOURCE"),
	SOLM_KW ("Description", "SOLM.KW"),
	SOLM_PB ("Partner XRN", "SOLM.PB"),
	SOLM_PA ("Partner", "SOLM.PA"),
	SOLM_SOL ("Solvent", "SOLM.SOL"),
	SOLM_T ("Temperature", "SOLM.T"),
	SOLM_P ("Pressure", "SOLM.P"),
	SOLM_ED ("Entry Date", "SOLM.ED"),
	SOLM_LCN ("Location", "SOLM.LCN"),
	SOLM_TAG ("Tag Location", "SOLM.TAG"),
	SOLM_COM ("Comment", "SOLM.COM"),
	LVSM_L ("Citation Pointer", "LVSM.L"),
	LVSM_SOURCE ("Source", "LVSM.SOURCE"),
	LVSM_KW ("Description", "LVSM.KW"),
	LVSM_PB ("Partner XRN", "LVSM.PB"),
	LVSM_PA ("Partner", "LVSM.PA"),
	LVSM_SOL ("Solvent", "LVSM.SOL"),
	LVSM_T ("Temperature", "LVSM.T"),
	LVSM_P ("Pressure", "LVSM.P"),
	LVSM_ED ("Entry Date", "LVSM.ED"),
	LVSM_LCN ("Location", "LVSM.LCN"),
	LVSM_TAG ("Tag Location", "LVSM.TAG"),
	LVSM_COM ("Comment", "LVSM.COM"),
	CPEM_L ("Citation Pointer", "CPEM.L"),
	CPEM_SOURCE ("Source", "CPEM.SOURCE"),
	CPEM_KW ("Description", "CPEM.KW"),
	CPEM_PB ("Partner XRN", "CPEM.PB"),
	CPEM_PA ("Partner", "CPEM.PA"),
	CPEM_SOL ("Solvent", "CPEM.SOL"),
	CPEM_T ("Temperature", "CPEM.T"),
	CPEM_P ("Pressure", "CPEM.P"),
	CPEM_ED ("Entry Date", "CPEM.ED"),
	CPEM_LCN ("Location", "CPEM.LCN"),
	CPEM_TAG ("Tag Location", "CPEM.TAG"),
	CPEM_COM ("Comment", "CPEM.COM"),
	LLSM_L ("Citation Pointer", "LLSM.L"),
	LLSM_SOURCE ("Source", "LLSM.SOURCE"),
	LLSM_KW ("Description", "LLSM.KW"),
	LLSM_PB ("Partner XRN", "LLSM.PB"),
	LLSM_PA ("Partner", "LLSM.PA"),
	LLSM_SOL ("Solvent", "LLSM.SOL"),
	LLSM_T ("Temperature", "LLSM.T"),
	LLSM_P ("Pressure", "LLSM.P"),
	LLSM_ED ("Entry Date", "LLSM.ED"),
	LLSM_LCN ("Location", "LLSM.LCN"),
	LLSM_TAG ("Tag Location", "LLSM.TAG"),
	LLSM_COM ("Comment", "LLSM.COM"),
	LSSM_L ("Citation Pointer", "LSSM.L"),
	LSSM_SOURCE ("Source", "LSSM.SOURCE"),
	LSSM_KW ("Description", "LSSM.KW"),
	LSSM_PB ("Partner XRN", "LSSM.PB"),
	LSSM_PA ("Partner", "LSSM.PA"),
	LSSM_SXRN ("System Component XRN", "LSSM.SXRN"),
	LSSM_SCOMP ("System Component", "LSSM.SCOMP"),
	LSSM_SOL ("Solvent", "LSSM.SOL"),
	LSSM_T ("Temperature", "LSSM.T"),
	LSSM_P ("Pressure", "LSSM.P"),
	LSSM_ED ("Entry Date", "LSSM.ED"),
	LSSM_LCN ("Location", "LSSM.LCN"),
	LSSM_TAG ("Tag Location", "LSSM.TAG"),
	LSSM_COM ("Comment", "LSSM.COM"),
	MECM_L ("Citation Pointer", "MECM.L"),
	MECM_SOURCE ("Source", "MECM.SOURCE"),
	MECM_KW ("Description", "MECM.KW"),
	MECM_PB ("Partner XRN", "MECM.PB"),
	MECM_PA ("Partner", "MECM.PA"),
	MECM_SOL ("Solvent", "MECM.SOL"),
	MECM_T ("Temperature", "MECM.T"),
	MECM_P ("Pressure", "MECM.P"),
	MECM_ED ("Entry Date", "MECM.ED"),
	MECM_LCN ("Location", "MECM.LCN"),
	MECM_TAG ("Tag Location", "MECM.TAG"),
	MECM_COM ("Comment", "MECM.COM"),
	TRAM_L ("Citation Pointer", "TRAM.L"),
	TRAM_SOURCE ("Source", "TRAM.SOURCE"),
	TRAM_KW ("Description", "TRAM.KW"),
	TRAM_PB ("Partner XRN", "TRAM.PB"),
	TRAM_PA ("Partner", "TRAM.PA"),
	TRAM_SOL ("Solvent", "TRAM.SOL"),
	TRAM_T ("Temperature", "TRAM.T"),
	TRAM_P ("Pressure", "TRAM.P"),
	TRAM_ED ("Entry Date", "TRAM.ED"),
	TRAM_LCN ("Location", "TRAM.LCN"),
	TRAM_TAG ("Tag Location", "TRAM.TAG"),
	TRAM_COM ("Comment", "TRAM.COM"),
	ENEM_L ("Citation Pointer", "ENEM.L"),
	ENEM_SOURCE ("Source", "ENEM.SOURCE"),
	ENEM_KW ("Description", "ENEM.KW"),
	ENEM_PB ("Partner XRN", "ENEM.PB"),
	ENEM_PA ("Partner", "ENEM.PA"),
	ENEM_SOL ("Solvent", "ENEM.SOL"),
	ENEM_T ("Temperature", "ENEM.T"),
	ENEM_P ("Pressure", "ENEM.P"),
	ENEM_ED ("Entry Date", "ENEM.ED"),
	ENEM_LCN ("Location", "ENEM.LCN"),
	ENEM_TAG ("Tag Location", "ENEM.TAG"),
	ENEM_COM ("Comment", "ENEM.COM"),
	BSPM_L ("Citation Pointer", "BSPM.L"),
	BSPM_SOURCE ("Source", "BSPM.SOURCE"),
	BSPM_KW ("Description", "BSPM.KW"),
	BSPM_PB ("Partner XRN", "BSPM.PB"),
	BSPM_PA ("Partner", "BSPM.PA"),
	BSPM_SOL ("Solvent", "BSPM.SOL"),
	BSPM_T ("Temperature", "BSPM.T"),
	BSPM_P ("Pressure", "BSPM.P"),
	BSPM_ED ("Entry Date", "BSPM.ED"),
	BSPM_LCN ("Location", "BSPM.LCN"),
	BSPM_TAG ("Tag Location", "BSPM.TAG"),
	BSPM_COM ("Comment", "BSPM.COM"),
	ADSM_L ("Citation Pointer", "ADSM.L"),
	ADSM_SOURCE ("Source", "ADSM.SOURCE"),
	ADSM_KW ("Description", "ADSM.KW"),
	ADSM_PB ("Partner XRN", "ADSM.PB"),
	ADSM_PA ("Partner", "ADSM.PA"),
	ADSM_SOL ("Solvent", "ADSM.SOL"),
	ADSM_T ("Temperature", "ADSM.T"),
	ADSM_P ("Pressure", "ADSM.P"),
	ADSM_ED ("Entry Date", "ADSM.ED"),
	ADSM_LCN ("Location", "ADSM.LCN"),
	ADSM_TAG ("Tag Location", "ADSM.TAG"),
	ADSM_COM ("Comment", "ADSM.COM"),
	ASSM_L ("Citation Pointer", "ASSM.L"),
	ASSM_SOURCE ("Source", "ASSM.SOURCE"),
	ASSM_KW ("Description", "ASSM.KW"),
	ASSM_PB ("Partner XRN", "ASSM.PB"),
	ASSM_PA ("Partner", "ASSM.PA"),
	ASSM_SOL ("Solvent", "ASSM.SOL"),
	ASSM_T ("Temperature", "ASSM.T"),
	ASSM_P ("Pressure", "ASSM.P"),
	ASSM_ED ("Entry Date", "ASSM.ED"),
	ASSM_LCN ("Location", "ASSM.LCN"),
	ASSM_TAG ("Tag Location", "ASSM.TAG"),
	ASSM_COM ("Comment", "ASSM.COM"),
	ECTD_L ("Citation Pointer", "ECTD.L"),
	ECTD_SOURCE ("Source", "ECTD.SOURCE"),
	ECTD_TY ("Type", "ECTD.TY"),
	ECTD_ME ("Media", "ECTD.ME"),
	ECTD_RE ("Results", "ECTD.RE"),
	ECTD_MR ("Method, Remarks", "ECTD.MR"),
	ECTD_ED ("Entry Date", "ECTD.ED"),
	ECTD_LCN ("Location", "ECTD.LCN"),
	ECTD_TAG ("Tag Location", "ECTD.TAG"),
	ECTD_COM ("Comment", "ECTD.COM"),
	BIOD_L ("Citation Pointer", "BIOD.L"),
	BIOD_SOURCE ("Source", "BIOD.SOURCE"),
	BIOD_TY ("Type", "BIOD.TY"),
	BIOD_IN ("Inoculum", "BIOD.IN"),
	BIOD_C ("Concentration", "BIOD.C"),
	BIOD_D ("Degradation Rate", "BIOD.D"),
	BIOD_E ("Exposure Period", "BIOD.E"),
	BIOD_T ("Temperature", "BIOD.T"),
	BIOD_H ("Half-life Time", "BIOD.H"),
	BIOD_XRN ("Degradation Product XRN", "BIOD.XRN"),
	BIOD_DP ("Degradation Product", "BIOD.DP"),
	BIOD_MR ("Method, Remarks", "BIOD.MR"),
	BIOD_ED ("Entry Date", "BIOD.ED"),
	BIOD_LCN ("Location", "BIOD.LCN"),
	BIOD_TAG ("Tag Location", "BIOD.TAG"),
	BIOD_COM ("Comment", "BIOD.COM"),
	ECDH_L ("Citation Pointer", "ECDH.L"),
	ECDH_SOURCE ("Source", "ECDH.SOURCE"),
	ECDH_TY ("Type", "ECDH.TY"),
	ECDH_C ("Concentration", "ECDH.C"),
	ECDH_D ("Degradation Rate", "ECDH.D"),
	ECDH_E ("Exposure Period", "ECDH.E"),
	ECDH_T ("Temperature", "ECDH.T"),
	ECDH_RC ("Rate Constant", "ECDH.RC"),
	ECDH_PH ("pH-Value", "ECDH.PH"),
	ECDH_H ("Half-life Time", "ECDH.H"),
	ECDH_XRN ("Degradation Product XRN", "ECDH.XRN"),
	ECDH_DP ("Degradation Product", "ECDH.DP"),
	ECDH_MR ("Method, Remarks", "ECDH.MR"),
	ECDH_ED ("Entry Date", "ECDH.ED"),
	ECDH_LCN ("Location", "ECDH.LCN"),
	ECDH_TAG ("Tag Location", "ECDH.TAG"),
	ECDH_COM ("Comment", "ECDH.COM"),
	ECDP_SOURCE ("Source", "ECDP.SOURCE"),
	ECDP_TY ("Type", "ECDP.TY"),
	ECDP_C ("Concentration", "ECDP.C"),
	ECDP_D ("Degradation Rate", "ECDP.D"),
	ECDP_E ("Exposure Period", "ECDP.E"),
	ECDP_T ("Temperature", "ECDP.T"),
	ECDP_RC ("Rate Constant", "ECDP.RC"),
	ECDP_PH ("pH-Value", "ECDP.PH"),
	ECDP_H ("Half-life Time", "ECDP.H"),
	ECDP_XRN ("Degradation Product XRN", "ECDP.XRN"),
	ECDP_DP ("Degradation Product", "ECDP.DP"),
	ECDP_MR ("Method, Remarks", "ECDP.MR"),
	ECDP_ED ("Entry Date", "ECDP.ED"),
	ECDP_LCN ("Location", "ECDP.LCN"),
	ECDP_TAG ("Tag Location", "ECDP.TAG"),
	ECDP_COM ("Comment", "ECDP.COM"),
	QUAN_L ("Citation Pointer", "QUAN.L"),
	QUAN_SOURCE ("Source", "QUAN.SOURCE"),
	QUAN_PROP ("Calculated Properties", "QUAN.PROP"),
	QUAN_MET ("Method", "QUAN.MET"),
	QUAN_ED ("Entry Date", "QUAN.ED"),
	QUAN_LCN ("Location", "QUAN.LCN"),
	QUAN_TAG ("Tag Location", "QUAN.TAG"),
	QUAN_COM ("Comment", "QUAN.COM"),
	ALLOY_FORM ("Formula", "ALLOY.FORM"),
	ALLOY_W ("Weight Percentage", "ALLOY.W"),
	ALLOY_A ("Atom Percentage", "ALLOY.A"),
	ALLOY_V ("Volume Percentage", "ALLOY.V"),
	ALLOY_X ("Undefined Percentage", "ALLOY.X"),
	EXTID_CASRN ("CAS Registry Number", "EXTID.CASRN"),
	EXTID_INCHI ("InChI Code", "EXTID.INCHI"),
	CRYPH_L ("Citation Pointer", "CRYPH.L"),
	CRYPH_SOURCE ("Source", "CRYPH.SOURCE"),
	CRYPH_KW ("Description", "CRYPH.KW"),
	CRYPH_T ("Temperature", "CRYPH.T"),
	CRYPH_ED ("Entry Date", "CRYPH.ED"),
	CRYPH_LCN ("Location", "CRYPH.LCN"),
	CRYPH_TAG ("Tag Location", "CRYPH.TAG"),
	CRYPH_COM ("Comment", "CRYPH.COM"),
	LIQPH_L ("Citation Pointer", "LIQPH.L"),
	LIQPH_SOURCE ("Source", "LIQPH.SOURCE"),
	LIQPH_KW ("Description", "LIQPH.KW"),
	LIQPH_ED ("Entry Date", "LIQPH.ED"),
	LIQPH_LCN ("Location", "LIQPH.LCN"),
	LIQPH_TAG ("Tag Location", "LIQPH.TAG"),
	LIQPH_COM ("Comment", "LIQPH.COM"),
	SOUND_L ("Citation Pointer", "SOUND.L"),
	SOUND_SOURCE ("Source", "SOUND.SOURCE"),
	SOUND_KW ("Description", "SOUND.KW"),
	SOUND_ED ("Entry Date", "SOUND.ED"),
	SOUND_LCN ("Location", "SOUND.LCN"),
	SOUND_TAG ("Tag Location", "SOUND.TAG"),
	SOUND_COM ("Comment", "SOUND.COM"),
	FINFO_SOURCE ("Source", "FINFO.SOURCE"),
	FINFO_KW ("Description", "FINFO.KW"),
	FINFO_KW2 ("Additional Description", "FINFO.KW2"),
	FINFO_ED ("Entry Date", "FINFO.ED"),
	FINFO_LCN ("Location", "FINFO.LCN"),
	FINFO_TAG ("Tag Location", "FINFO.TAG"),
	FINFO_COM ("Comment", "FINFO.COM"),
	RAMAN_L ("Citation Pointer", "RAMAN.L"),
	RAMAN_SOURCE ("Source", "RAMAN.SOURCE"),
	RAMAN_KW ("Description", "RAMAN.KW"),
	RAMAN_SOL ("Solvent", "RAMAN.SOL"),
	RAMAN_ED ("Entry Date", "RAMAN.ED"),
	RAMAN_LCN ("Location", "RAMAN.LCN"),
	RAMAN_TAG ("Tag Location", "RAMAN.TAG"),
	RAMAN_COM ("Comment", "RAMAN.COM"),
	PHARM_L ("Citation Pointer", "PHARM.L"),
	PHARM_SOURCE ("Source", "PHARM.SOURCE"),
	PHARM_E ("Effect", "PHARM.E"),
	PHARM_EP ("Endpoint of Effect", "PHARM.EP"),
	PHARM_SP ("Species or Test-System", "PHARM.SP"),
	PHARM_S ("Sex", "PHARM.S"),
	PHARM_RA ("Route of Application", "PHARM.RA"),
	PHARM_C ("Concentration", "PHARM.C"),
	PHARM_KD ("Kind of Dosing", "PHARM.KD"),
	PHARM_EX ("Exposure Period", "PHARM.EX"),
	PHARM_MR ("Method", "PHARM.MR"),
	PHARM_FD ("Further Details", "PHARM.FD"),
	PHARM_H ("Half-life Time", "PHARM.H"),
	PHARM_TY ("Type", "PHARM.TY"),
	PHARM_V ("Value of Type", "PHARM.V"),
	PHARM_RE ("Results", "PHARM.RE"),
	PHARM_XRN ("Metabolite XRN", "PHARM.XRN"),
	PHARM_META ("Metabolite", "PHARM.META"),
	PHARM_ED ("Entry Date", "PHARM.ED"),
	PHARM_LCN ("Location", "PHARM.LCN"),
	PHARM_TAG ("Tag Location", "PHARM.TAG"),
	PHARM_COM ("Comment", "PHARM.COM"),
	SOVERW_NTARG ("Number of Targets", "SOVERW.NTARG"),
	SOVERW_NBACT ("Number of Bioactivities", "SOVERW.NBACT"),
	TARGET_ID ("Target ID", "TARGET.ID"),
	TARGET_ED ("Entry Date", "TARGET.ED"),
	TARGET_UPD("Entry Date", "TARGET.UPD"),
	TARGET_CIT ("Citation Pointer", "TARGET.CIT"),
	TARGET_SRC ("Source", "TARGET.SRC"),
	TARGET_ASSAY ("Bioassay Pointer", "TARGET.ASSAY"),
	TARGET_ATYPE ("Bioassay Type", "TARGET.ATYPE"),
	TARGET_NAME ("Target name", "TARGET.NAME"),
	TARGET_SPECIE ("Target species", "TARGET.SPECIE"),
	TARGET_SITE ("Compound action site", "TARGET.SITE"),
	TARGET_ROLE ("Target role", "TARGET.ROLE"),
	TARGET_NATURE ("Target nature", "TARGET.NATURE"),
	TARGET_ABBREV ("Abbreviation", "TARGET.ABBREV"),
	TARGET_SYNONYM ("Synonym", "TARGET.SYNONYM"),
	TARGET_CLASS ("Target class", "TARGET.CLASS"),
	TARGET_DETAILS ("Mutant-Chimera details", "TARGET.DETAILS"),
	TARGET_GENETREE ("Genetree", "TARGET.GENETREE"),
	TARGET_UNIPROT ("Uniprot", "TARGET.UNIPROT"),
	TARGET_PDB ("PDB", "TARGET.PDB"),
	TARGET_KEY ("Target key", "TARGET.KEY"),
	TARGET_SKEY ("Target short key", "TARGET.SKEY"),
	TARGET_ASPECIE ("All species", "TARGET.ASPECIE"),
	TARGET_ANAME ("All targets", "TARGET.ANAME"),
	TOVERW_NCOMP ("Number of Compounds", "TOVERW.NCOMP"),
	TOVERW_NBACT ("Number of Bioactivities", "TOVERW.NBACT"),
	TOVERW_NREF ("Number of References", "TOVERW.NREF"),
	TOVERW_MAXARN ("Most active Compound RN", "TOVERW.MAXARN"),
	TOVERW_MAXVAL ("Activity at most active Compound", "TOVERW.MAXVAL"),
	SUBLINK_NAME ("Database", "SUBLINK.NAME"),
	SUBLINK_KEY ("Primary Key", "SUBLINK.KEY"),
	CLPHASE_VALUE ("Highest Clinical Phase", "CLPHASE.VALUE"),
	RXNLINK_NAME ("Database", "RXNLINK.NAME"),
	RXNLINK_OTH_RXN ("Reaction Foreign Key", "RXNLINK.OTH_RXN"),
	RXNLINK_OWN_SUB ("Substance Own Key", "RXNLINK.OWN_SUB"),
	RXNLINK_OTH_SUB ("Substance Foreign Key", "RXNLINK.OTH_SUB"),
	CHROMAT_L ("Citation Pointer", "CHROMAT.L"),
	CHROMAT_SOURCE ("Source", "CHROMAT.SOURCE"),
	CHROMAT_CHROMAT ("Chromatographic data", "CHROMAT.CHROMAT"),
	CHROMAT_CHROMATSTRING ("Original string", "CHROMAT.CHROMATSTRING"),
	CHROMAT_ED ("Entry Date", "CHROMAT.ED"),
	CHROMAT_LCN ("Location", "CHROMAT.LCN"),
	CHROMAT_TAG ("Tag Location", "CHROMAT.TAG"),
	CHROMAT_COM ("Comment", "CHROMAT.COM"),
	SUBUNIT_PROTP ("Protein Pointer", "SUBUNIT.PROTP"),
	SUBUNIT_NAME ("Subunit Name", "SUBUNIT.NAME"),
	SUBUNIT_SYNONYM ("Subunit Synonym", "SUBUNIT.SYNONYM"),
	SUBUNIT_PROTN ("Subunit protein", "SUBUNIT.PROTN"),
	SUBUNIT_SPECIE ("Subunit species", "SUBUNIT.SPECIE"),
	SUBUNIT_NATURE ("Protein nature", "SUBUNIT.NATURE"),
	SUBUNIT_TRANSFECT ("Transfection", "SUBUNIT.TRANSFECT"),
	SUBUNIT_STOICHIO ("Stoichiometry", "SUBUNIT.STOICHIO"),
	SUBUNIT_ACTSITE ("Active site indicator", "SUBUNIT.ACTSITE"),
	SUBUNIT_PMID ("Promoter identifier", "SUBUNIT.PMID"),
	SUBUNIT_PMPROT ("Promoter protein", "SUBUNIT.PMPROT"),
	SUBUNIT_PMSPECIE ("Promoter species", "SUBUNIT.PMSPECIE"),
	PUBCHEM_HEADING("Heading", "TB.HEADING"),
	SUPPLIER_PPG("Price per Gram", "SUPL.PRICEGRAM"),
	SUPPLIER_PPM("Price per Mol", "SUPL.PRICEMOL"),
	SUPPLIER_PPMM("Price per mMol", "SUPL.PRICEMMOL"),
	SUPPLIER_QUANT("Quantites",  "SUPL.QUANT"),
	SUPPLIER_LARGEST("Largest Quantity", "SUPL.MAXQUANT"),
	SUPPLIER_COM("Comment", "SUPL.COMMENT"),
	SUPPLIER_TIER1("Tier 1 Suppliers", "SUPL.T1SUPL"),
	SUPPLIER_TIER2("Tier 2 Suppliers", "SUPL.T2SUPL"),
	SUPPLIER_TIER3("Tier 3 Suppliers", "SUPL.T3SUPL"),
	SUPPLIER_TIER4("Tier 4 Suppliers", "SUPL.T4SUPL"),
	SUPPLIER_TIER5("Tier 5 Suppliers", "SUPL.T5SUPL"),
	PROD_RCPID("Reaxys Commercial Product ID", "PROD.RCPID"),
	PROD_SPNR("Supplier product number", "PROD.SPNR"),
	PROD_CATPNR("Catalog Identification Number", "PROD.CATPNR"),
	PROD_SKU("Supplier SKU", "PROD.SKU"),
	PROD_PNAME("Product name", "PROD.PNAME"),
	PROD_PURL("Direct link URL (Supplier hop-into)", "PROD.PURL"),
	PROD_PUPD("Last update", "PROD.PUPD"),
	PROD_PRICE("Price", "PROD.PRICE"),
	PROD_CURRENCY("Currency", "PROD.CURRENCY"),
	PROD_PRICET("Price text", "PROD.PRICET"),
	PROD_PACKSZ("Package size", "PROD.PACKSZ"),
	PROD_PACKSZN("Package size normalized", "PROD.PACKSZN"),
	PROD_PURITY("Purity (%)", "PROD.PURITY"),
	PROD_PURITYT("Purity (free text)", "PROD.PURITYT"),
	PROD_STOCK("Stock status ", "PROD.STOCK"),
	PROD_SHIPTIME("Shipment time ", "PROD.SHIPTIME"),
	PROD_TIER("Shipment (Availability) Tier ", "PROD.TIER"),
	/* ADD:
	 * References 
	 * Vendor/Supplier ID
	 * Company Name
	 * Company Name Synonyms
	 * 
	 * */
	
	
	
	/*  ELN fields */
	RX_CCID("Customer Content Reaction ID ", "RX.CCID"),
	RX_RCCRN("Reactant CCRN ", "RX.RCCRN"),
	RX_PCCRN("Product CCRN ", "RX.PCCRN"),
	RX_MCCRN("Metabolite CCRN ", "RX.MCCRN"),
	RX_META("Metabolite ", "RX.META"),
	RX_NAVAIL("Foreign Database Availability ", "RX.NAVAIL"),
	RX_SCIENTIST("Scientist Sort Field ", "RX.SCIENTIST"),
	RX_PROJNAME("Project Sort Field ", "RX.PROJNAME"),
	RX_SCALE("Reaction Scale Sort Field, mol ", "RX.SCALE"),
	RX_CDATE("Creation Date Sort Field ", "RX.CDATE"),
	RX_MDATE("Modification Date Sort Field ", "RX.MDATE"),
	RX_RGT("Reagent Sort Field ", "RX.RGT"),
	RX_SOL("Solvent Sort Field ", "RX.SOL"),
	RX_CAT("Catalyst Sort Field ", "RX.CAT"),
	RX_RXNOREATYP("Reaction Name Sort Field ", "RX.RXNOREATYP"),
	RX_SITE("Created at Site Sort Field ", "RX.SITE"),
	RX_SOURCE("Source Sort Field ", "RX.SOURCE"),
	RX_TOTVOL("Total Volume Sort Field, l ", "RX.TOTVOL"),
	RX_REAMOL("Molarity Sort Field, mol/l ", "RX.REAMOL"),
	RX_STATUS("Status Sort Field ", "RX.STATUS"),
	RXD_VARID("Variation ID ", "RXD.VARID"),
	RXD_CDATE("Creation Date ", "RXD.CDATE"),
	RXD_EXPID("Experiment ID ", "RXD.EXPID"),
	RXD_EXPTYPE("Experiment Type ", "RXD.EXPTYPE"),
	RXD_MDATE("Modification Date ", "RXD.MDATE"),
	RXD_PROJNAME("Project ", "RXD.PROJNAME"),
	RXD_QUALIFICATION("Qualification ", "RXD.QUALIFICATION"),
	RXD_RANK("Rank ", "RXD.RANK"),
	RXD_CHEMIST("Chemist ", "RXD.CHEMIST"),
	RXD_PRODUCER("Producer ", "RXD.PRODUCER"),
	RXD_DESTINATION("Destination ", "RXD.DESTINATION"),
	RXD_COM_TYPE("Experiment Comment Type ", "RXD.COM_TYPE"),
	RXD_SYSCOM("System Comment ", "RXD.SYSCOM"),
	RXD_KW_TYPE("Keyword Type ", "RXD.KW_TYPE"),
	RXD_KW("Keyword ", "RXD.KW"),
	RXD_LK_TYPE("Experiment Link Type ", "RXD.LK_TYPE"),
	RXD_LK("Experiment Link ", "RXD.LK"),
	RXD_NUMEX("Experiment Identifier Exists ", "RXD.NUMEX"),
	RXD_EXTID("Experiment Identifier ", "RXD.EXTID"),
	RXD_EXTID_TYPE("Experiment Identifier Type ", "RXD.EXTID_TYPE"),
	RXD_CONC("Conclusion Phrase ", "RXD.CONC"),
	RXD_SITE("Created at Site ", "RXD.SITE"),
	RXD_DUPEXPREF("Duplicate Experiment Reference ", "RXD.DUPEXPREF"),
	RXD_ELNCIT("ELN Citation ", "RXD.ELNCIT"),
	RXD_NXMOVREATYP("NextMove Reaction Type ", "RXD.NXMOVREATYP"),
	RXD_STATUS("Status ", "RXD.STATUS"),
	RXD_RXNOREATYP("Reaction Name ", "RXD.RXNOREATYP"),
	RXD_ADEXISTS("Analytical Data Exist ", "RXD.ADEXISTS"),
	RXD_SCALE("Reaction Scale ", "RXD.SCALE"),
	RXD_PREP("Preparative ", "RXD.PREP"),
	RXD_CUSTID1("Customer ID1 ", "RXD.CUSTID1"),
	RXD_CUSTID2("Customer ID2 ", "RXD.CUSTID2"),
	RXD_CUSTID3("Customer ID3 ", "RXD.CUSTID3"),
	RXD_CUSTID4("Customer ID4 ", "RXD.CUSTID4"),
	RXD_SCIENTIST("Scientist ", "RXD.SCIENTIST"),
	RXD_DRGTCCRN("Reagent CCRN ", "RXD.DRGTCCRN"),
	RXD_DRGT("Reagent ", "RXD.DRGT"),
	RXD_DRGTAMOUNT("Reagent Amount, mol ", "RXD.DRGTAMOUNT"),
	RXD_DRGTFORM("Reagent Form ", "RXD.DRGTFORM"),
	RXD_DRGTCOLOR("Reagent Color ", "RXD.DRGTCOLOR"),
	RXD_DRGTSAM("Reagent Sample ", "RXD.DRGTSAM"),
	RXD_DRGTCNAME("Reagent Compound Name ", "RXD.DRGTCNAME"),
	RXD_DRGTVOL("Reagent Volume, l ", "RXD.DRGTVOL"),
	RXD_DRGTEQUIV("Reagent Equivalents ", "RXD.DRGTEQUIV"),
	RXD_DRGTCOM("Reagent Comment ", "RXD.DRGTCOM"),
	RXD_DCATCCRN("Catalyst CCRN ", "RXD.DCATCCRN"),
	RXD_DCAT("Catalyst ", "RXD.DCAT"),
	RXD_DCATAMOUNT("Catalyst Amount, mol ", "RXD.DCATAMOUNT"),
	RXD_DCATFORM("Catalyst Form ", "RXD.DCATFORM"),
	RXD_DCATCOLOR("Catalyst Color ", "RXD.DCATCOLOR"),
	RXD_DCATVOL("Catalyst Volume, l ", "RXD.DCATVOL"),
	RXD_DCATSAM("Catalyst Sample ", "RXD.DCATSAM"),
	RXD_DCATCNAME("Catalyst Compound Name ", "RXD.DCATCNAME"),
	RXD_DCATCOM("Catalyst Comment ", "RXD.DCATCOM"),
	RXD_DSOLCCRN("Solvent CCRN ", "RXD.DSOLCCRN"),
	RXD_DSOL("Solvent ", "RXD.DSOL"),
	RXD_DSOLVOL("Solvent Volume, l ", "RXD.DSOLVOL"),
	RXD_DSOLAMOUNT("Solvent Amount, mol ", "RXD.DSOLAMOUNT"),
	RXD_DSOLFORM("Solvent Form ", "RXD.DSOLFORM"),
	RXD_DSOLCOLOR("Solvent Color ", "RXD.DSOLCOLOR"),
	RXD_DSOLSAM("Solvent Sample ", "RXD.DSOLSAM"),
	RXD_DSOLCNAME("Solvent Compound Name ", "RXD.DSOLCNAME"),
	RXD_DSOLCOM("Solvent Comment ", "RXD.DSOLCOM"),
	RXD_RCCRN("Reactant CCRN ", "RXD.RCCRN"),
	RXD_RCT("Reactant ", "RXD.RCT"),
	RXD_RAMOUNT("Reactant Amount, mol ", "RXD.RAMOUNT"),
	RXD_REQUIV("Reactant Equivalents ", "RXD.REQUIV"),
	RXD_RFORM("Reactant Form ", "RXD.RFORM"),
	RXD_RCOLOR("Reactant Color ", "RXD.RCOLOR"),
	RXD_RSAM("Reactant Sample ", "RXD.RSAM"),
	RXD_RCNAME("Reactant Compound Name ", "RXD.RCNAME"),
	RXD_RVOL("Reactant Volume, l ", "RXD.RVOL"),
	RXD_RCOM("Reactant Comment ", "RXD.RCOM"),
	RXD_YCCRN("Product CCRN ", "RXD.YCCRN"),
	RXD_PAMOUNT("Product Amount, mol ", "RXD.PAMOUNT"),
	RXD_PCOLOR("Product Color ", "RXD.PCOLOR"),
	RXD_PFORM("Product Form ", "RXD.PFORM"),
	RXD_PSAM("Product Sample ", "RXD.PSAM"),
	RXD_PCNAME("Product Compound Name ", "RXD.PCNAME"),
	RXD_CONV("Conversion, percent ", "RXD.CONV"),
	RXD_PPUR("Product Pure, percent ", "RXD.PPUR"),
	RXD_PENANPUR("Product Enantiomeric Purity, percent ", "RXD.PENANPUR"),
	RXD_PEQUIV("Product Equivalents ", "RXD.PEQUIV"),
	RXD_PCOM("Product Comment ", "RXD.PCOM"),
	RXD_DATMOS("Atmosphere ", "RXD.DATMOS"),
	RXD_DTXT("Experimental Procedure ", "RXD.DTXT"),
	RXD_DP("Pressure, Torr ", "RXD.DP"),
	RXD_DPH("pH-Value ", "RXD.DPH"),
	RXD_DCOND("Other Conditions ", "RXD.DCOND"),
	RXD_DREAMOL("Molarity, mol/l ", "RXD.DREAMOL"),
	RXD_DTOTVOL("Total Volume, l ", "RXD.DTOTVOL"),
	RXD_FUNCTIONAL("Functional Group ", "RXD.FUNCTIONAL"),
	RXD_PROTECTING("Protecting Group ", "RXD.PROTECTING"),
	RXD_TOLERATED("Tolerated Group ", "RXD.TOLERATED"),
	RXD_EXAMPLE_CIT_ID("Group Example Citation ", "RXD.EXAMPLE_CIT_ID"),
	RXD_EXAMPLE_TYPE("Group Example Type ", "RXD.EXAMPLE_TYPE"),
	RXD_EXAMPLE_CONDITION("Group Example Conditions ", "RXD.EXAMPLE_CONDITION"),
	RXD_EXAMPLE_COMMENT("Group Example Comment ", "RXD.EXAMPLE_COMMENT"),
	RXD_ANIMAL_CIT_REF("Animal Citation ", "RXD.ANIMAL_CIT_REF"),
	RXD_SPECIES("Metabolization Species ", "RXD.SPECIES"),
	RXD_ROUTE("Metabolization Route ", "RXD.ROUTE"),
	RXD_EXCRETION("Metabolization Excretion ", "RXD.EXCRETION"),
	RXD_ENZYMES_ECNUM("Enzymes EC Number ", "RXD.ENZYMES_ECNUM"),
	RXD_REFID("Reference ID ", "RXD.REFID"),
	RXD_REFORD("Reference Order ", "RXD.REFORD"),
	RXD_REFPATH("Reference Path ", "RXD.REFPATH"),
	RXD_RESP_SCIENTIST("Responsible Scientist ", "RXD.RESP_SCIENTIST"),
	RXD_GROUP("Group ", "RXD.GROUP"),
	RXD_AB("Experiment Abstract ", "RXD.AB"),
	RXD_ATMOS("Atmosphere ", "RXD.ATMOS"),
	RXD_STGTXT("Experimental Procedure ", "RXD.STGTXT"),
	RXD_REAMOL("Molarity, mol/l ", "RXD.REAMOL"),
	RXD_TOTVOL("Total Volume, l ", "RXD.TOTVOL"),
	RXD_RGTCCRN("Reagent CCRN ", "RXD.RGTCCRN"),
	RXD_RGTAMOUNT("Reagent Amount, mol ", "RXD.RGTAMOUNT"),
	RXD_RGTFORM("Reagent Form ", "RXD.RGTFORM"),
	RXD_RGTCOLOR("Reagent Color ", "RXD.RGTCOLOR"),
	RXD_RGTSAM("Reagent Sample ", "RXD.RGTSAM"),
	RXD_RGTCNAME("Reagent Compound Name ", "RXD.RGTCNAME"),
	RXD_RGTVOL("Reagent Volume, l ", "RXD.RGTVOL"),
	RXD_RGTEQUIV("Reagent Equivalents ", "RXD.RGTEQUIV"),
	RXD_RGTCOM("Reagent Comment ", "RXD.RGTCOM"),
	RXD_CATCCRN("Catalyst CCRN ", "RXD.CATCCRN"),
	RXD_CATAMOUNT("Catalyst Amount, mol ", "RXD.CATAMOUNT"),
	RXD_CATFORM("Catalyst Form ", "RXD.CATFORM"),
	RXD_CATCOLOR("Catalyst Color ", "RXD.CATCOLOR"),
	RXD_CATVOL("Catalyst Volume, l ", "RXD.CATVOL"),
	RXD_CATSAM("Catalyst Sample ", "RXD.CATSAM"),
	RXD_CATCNAME("Catalyst Compound Name ", "RXD.CATCNAME"),
	RXD_CATCOM("Catalyst Comment ", "RXD.CATCOM"),
	RXD_SOLCCRN("Solvent CCRN ", "RXD.SOLCCRN"),
	RXD_SOLVOL("Solvent Volume, l ", "RXD.SOLVOL"),
	RXD_SOLAMOUNT("Solvent Amount, mol ", "RXD.SOLAMOUNT"),
	RXD_SOLFORM("Solvent Form ", "RXD.SOLFORM"),
	RXD_SOLCOLOR("Solvent Color ", "RXD.SOLCOLOR"),
	RXD_SOLSAM("Solvent Sample ", "RXD.SOLSAM"),
	RXD_SOLCNAME("Solvent Compound Name ", "RXD.SOLCNAME"),
	RXD_SOLCOM("Solvent Comment ", "RXD.SOLCOM"),
	RXD_SRCCRN("Reactant CCRN ", "RXD.SRCCRN"),
	RXD_SRAMOUNT("Reactant Amount, mol ", "RXD.SRAMOUNT"),
	RXD_SREQUIV("Reactant Equivalents ", "RXD.SREQUIV"),
	RXD_SRFORM("Reactant Form ", "RXD.SRFORM"),
	RXD_SRCOLOR("Reactant Color ", "RXD.SRCOLOR"),
	RXD_SRSAM("Reactant Sample ", "RXD.SRSAM"),
	RXD_SRCNAME("Reactant Compound Name ", "RXD.SRCNAME"),
	RXD_SRVOL("Reactant Volume, l ", "RXD.SRVOL"),
	RXD_SRCOM("Reactant Comment ", "RXD.SRCOM"),
	RXD_SPCCRN("Product CCRN ", "RXD.SPCCRN"),
	RXD_SYPRO("Product ", "RXD.SYPRO"),
	RXD_SPAMOUNT("Product Amount, mol ", "RXD.SPAMOUNT"),
	RXD_SPCOLOR("Product Color ", "RXD.SPCOLOR"),
	RXD_SPFORM("Product Form ", "RXD.SPFORM"),
	RXD_SPSAM("Product Sample ", "RXD.SPSAM"),
	RXD_SPCNAME("Product Compound Name ", "RXD.SPCNAME"),
	RXD_SYD("Yield, percent ", "RXD.SYD"),
	RXD_SPCONV("Conversion, percent ", "RXD.SPCONV"),
	RXD_SPPUR("Product Pure, percent ", "RXD.SPPUR"),
	RXD_SPENANPUR("Product Enantiomeric Purity, percent ", "RXD.SPENANPUR"),
	RXD_SPEQUIV("Product Equivalents ", "RXD.SPEQUIV"),
	RXD_SPCOM("Product Comment ", "RXD.SPCOM"),
	IDE_CCRN("Customer Content Registry Number ", "IDE.CCRN");

	private String label;
	private String name;
	private static HashMap<String, String> lookupHash = null;
	
	ReaxysFieldTypes(String label, String name) {
		// make the label contain the field name as well as the description
		this.label = label + " (" + name + ")";
		this.name = name;
	}
	
	/**
	 * 
	 * @return
	 */
	String getLabel() {
		return label;
	}
	
	String getName() {
		return name;
	}
	
	/**
	 * get the list of labels for this class for the field browser
	 * @param claz class, e.g. RXD.  Note the period is important
	 * 
	 * @return arraylist of the labels for this class
	 */
	public static ArrayList<String>getLabelsForClass(final String claz) {
		
		ArrayList<String> result = new ArrayList<String>();
		
		for (final ReaxysFieldTypes v : ReaxysFieldTypes.values()) {
			if (v.getName().startsWith(claz)) {
			result.add(v.getLabel());
			}
		}
		Collections.sort(result);
		return result;
	}

	/**
	 * get the nice label for a field name.
	 * 
	 * @param name code for field name
	 * @return pretty label, or the original name if there is no mapping
	 */
	public static String getLabel(final String name) {
		
		if (lookupHash == null) {
			lookupHash = new HashMap<String, String>();
			for (final ReaxysFieldTypes v : ReaxysFieldTypes.values()) {
				lookupHash.put(v.getName(), v.getLabel());
			}
		}
		
		final String tempName = name.toUpperCase();
		
		String result = lookupHash.get(tempName);
		if (result != null) {
			return result;
		}

		// default - return the original name
		return name;
	}
}

